### ISSUE TITLE
RFC: keep record of perform count

### ISSUE THREAD

**Issue by pjcarly** [machty/ember-concurrency#101]
It would be very helpful to expose an integer on task, that keeps track of the times the task ran.
For me this would be helpful, as i'm running a task after component.init, and I would like to only show certain parts of my template when a certain task ran at least once.

**Comment by machty** [comment]
Is knowing the exact count important? Could you just make use of the fact that `someTask.last` will be null until the first time you run the task?

**Comment by pjcarly** [comment]
The exact count is not important for me, was just thinking of possible use cases in the future.
I will use .last to start.

**Comment by machty** [comment]
Closing for now but please comment if you run into any use cases where knowing the count would help.

**Comment by machty** [comment]
FYI someone else asked for this so it now exists as `task.performCount`, released in 0.8.0.

**Comment by pjcarly** [comment]
Aces! Thanks for the update. I'll try it out asap.
