### ISSUE TITLE
ember-getowner-polyfill.import deprecation

### ISSUE THREAD

**Issue by thomblake** [machty/ember-concurrency#106]
I believe this deprecation starts happening after Ember 2.9; I can't find the actual deprecation link

ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]

**Comment by alexander-alvarez** [comment]
https://github.com/machty/ember-concurrency/pull/103

**Comment by machty** [comment]
@thomblake if you upgrade ember-concurrency to the latest, do you still see this? (and are you sure it's ember-concurrency and not some other plugin? for me it was ember-responsive)

**Comment by jordpo** [comment]
I was getting the same thing with ember-simple-auth which does have the polyfill listed as a dependency.

**Comment by machty** [comment]
I'm pretty certain EC isn't the cause.
