### ISSUE TITLE
New this.myTask.perform() syntax not working from within a Mixin

### ISSUE THREAD

**Issue by denchen** [machty/ember-concurrency#114]
I have the following mixin similar to the following:

    import Ember from 'ember';
    import { task } from 'ember-concurrency';
    
    export default Ember.mixin.create({
      myTask1: task(function* () {
        // stuff
      }),

      myTask2: task(function* () {
        // more stuff
      }),

      actions: {
        handleTask1() {
          // this.get('myTask1').perform();
          this.myTask1.perform();
        }
      }
    });

I import this mixin in various Routes basically like this:

    import 'Ember' from 'ember';
    import MyTasksMixin from 'my-tasks-mixin';
   
    export default Ember.Route.extend(MyTasksMixin, {
      model() {
        // this.get('myTask2').perform();
        this.myTask2.perform();
      }
    });

I can't get the new syntax to work in either situation above for `myTask1` or `myTask2`. I basically get:

    Uncaught TypeError: this.myTask1.perform is not a function

The original syntax of `this.get('myTask1').perform()` works just fine. So I guess my question is, is this a bug, or is this something I shouldn't be doing with regards of how I've implemented my mixin?

**Comment by machty** [comment]
`.get()`-less access had to be [reverted](https://github.com/machty/ember-concurrency/blob/master/CHANGELOG.md#0715) due to insurmountable compatibility issues between versions of Ember. Sorry about that :(
