### ISSUE TITLE
Task gets lost in component after saving page

### ISSUE THREAD

**Issue by bluscreen** [machty/ember-concurrency#125]
Hi,

first of all, I really think this is a great plugin. It helped me with some issues i've been dealing with for a long time.
However, I have one use case where I could really need it:
I have several property observers firing an action to calculate some monetary value and i need them to wait a while before the user input stops since there can be dependent observers.
So in this action I'm calling the pbTask trying to prevent duplicate executions and waiting for the user input to finish

I put some debug logs into my task to see if its executed:
```
 pbTask: task(function*(risiko, key) {
        Ember.Logger.debug('PB task triggered', risiko)
        if (Ember.isEmpty(risiko)) {
            Ember.Logger.error("Risiko null pbTask")
            return
        }
        yield timeout(1000)
        Ember.Logger.debug("YIELDED...", risiko)
        this.pbFunc(risiko, key)
    }).drop(),
```
Everything works just fine until i save the the model a few times. then there will not be any more debug output coming from the task and its function wont be called any longer.

I also tryied with keepLatest() but it shows same behaviour...

I think this might be a bug since I haven't willingly done anything to deregister my task from the component and it is not null either. Any help will be welcome..

Best regards,

Daniel

**Comment by machty** [comment]
I recommend heading over to the `#e-concurrency` channel in the Ember Community Slack for help debugging something like this. It _might_ be a bug but either way you're likely the get quicker feedback there than in GH issues.

**Comment by bluscreen** [comment]
wow, what a quick response. thank you very much I will do so :-)
