### ISSUE TITLE
typeahead perform with html input field vs input helper

### ISSUE THREAD

**Issue by tarponjargon** [machty/ember-concurrency#126]
To be clear, this is not an issue with ember-concurrency.  But I think you may have encountered it and I'm wondering if you have any solutions.

I followed your instructions to create a typeahead function, and it works great when the input field is regular html like this:

`<input type="text" autocomplete="off" class="search-field form-control" name="saerchTerm" oninput={{perform autoSuggest value="target.value"}} placeholder="Search for something..." />`

The problem arises when I try to use an ember input helper instead:

```

{{input
	autocomplete="off"
	class="search-field form-control"
	value=searchTerm
	key-up=(perform autoSuggest searchTerm)
	placeholder="Search for something..."
}}

```

The reason I want to use an input helper is because the primary purpose of the field is a keyword search for the site.  If I use a straight html field, the form submit will re-load the app, which is not desired.  So to stay in the context of the app I need to use an input helper (unless there's another way?)

With the straight html input I was able to use keys (like arrows and enter) to navigate and select autosuggest items.  But with the input helper I am not, because the 'key-up' event is "grabbing" the keystroke and re-running the perform. 

The obvious solution would be to use:

`change=(perform autoSuggest searchTerm)`

But that produces some strange results.  The autosuggest results don't appear *unless* I toggle my browser to the console.  Very strange indeed.

I am wondering if your typeahead example used an regular html input for this reason?  Or perhaps I am just doing something totally wrong!

**Comment by alexander-alvarez** [comment]
not directly answering your question, but you might have more predictable results using [`one-way-input`](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-input.md) with `e-c`.

**Comment by midget2000x** [comment]
I tried it as such:

```
				{{one-way-input
					value=searchTerm
					update=(action 'doAutoSuggest' (mut searchTerm))
					autocomplete="off"
					class="search-field form-control"
					placeholder="Search for something..."
				}}
```

But I could not get it to pick up my value (with or without 'value=').  In trying to debug _that_ I found this comment:

> ...[so effectively, one-way-controls is not necessary anymore, and discouraged in general because of being 40x slower](https://www.emberscreencasts.com/posts/118-ember-one-way-controls-addon). ...

Which worries me a bit.  I'm not sure I really need it though.  I think I just need to figure out a way to get either `change` to work, or have the `key-up` event call an action that will pass thru keystrokes to my autosuggest function _excluding_ arrows, enter and escape.

**Comment by midget2000x** [comment]
I kinda figured out a workaround by creating an action that only triggers the perform for keys not on my "reserved" key list

`
...
autoSuggest: task(function*(query) {...}).restartable(),
thisKey: null,
keyDown: function(e) {
	set(this, 'thisKey', e.keyCode); 
},
actions: { 
	doAutoSuggest(query) { // filter out nav keys
		if (!get(this, 'specialKeys').includes(get(this, 'thisKey'))) {
			get(this, 'autoSuggest').perform(query);
		}
	}
}
...
`

**Comment by alexander-alvarez** [comment]
oh that's new to me.. I haven't had any performance issues.

I was thinking of something like this:
https://ember-twiddle.com/8cc6e00930c41e7b1bb7f3be92c4699a?openFiles=controllers.application.js%2C

also have you looked at `ember-power-select` / `ember-basic-dropdown` as they might have all or most of the functionality you're interested in:
http://www.ember-power-select.com/cookbook/debounce-searches
https://www.ember-basic-dropdown.com/docs

**Comment by midget2000x** [comment]
interesting.  I think I will need to go with power-select once I realize that rolling my own is a bad idea!  :D

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

For posterity, [`ember-power-select-typeahead`](https://github.com/cibernox/ember-power-select-typeahead) is a commonly used community solution and popular addon that provides this functionality and works well with ember-concurrency tasks.
