### ISSUE TITLE
ember-getowner-polyfill is now deprecated

### ISSUE THREAD

**Issue by tsteuwer** [machty/ember-concurrency#129]
```DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]```

**Comment by machty** [comment]
Seems like a up of #106; you might need to upgrade your version of ember-concurrency. If you still see that deprecation, it's probably being caused by another addon.

**Comment by tsteuwer** [comment]
But I see it as part of your dependencies:

https://github.com/machty/ember-concurrency/blob/master/package.json#L63

**Comment by webark** [comment]
@tsteuwer still needs to be used for addons that want to support people using versions of ember prior to 2.3.

**Comment by tsteuwer** [comment]
@webark ahh, that sucks. It takes up like half the console everytime you make a change lol. But make sense :|.

@machty I found that it is actually this addon that causes it. When compiled (I'm using ember 2.11) it creates the following code (_emberGetownerPolyfill) for -task-property.js (https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L154):

compiled code:
```
      ....
      if (typeof this.fn === 'object') {
        var owner = (0, _emberGetownerPolyfill['default'])(this.context);
        var ownerInjection = owner ? owner.ownerInjection() : {};
        this._taskInstanceFactory = _emberConcurrencyEncapsulatedTask['default'].extend(ownerInjection, this.fn);
      }
     ....
```

**Comment by webark** [comment]
@tsteuwer what version of this addon are you using? Cause `getOwner` gets destructured out of the Ember object at the top of that file like it should. But that compiled code looks like it got imported. And this is the browser console, not the terminal right?

**Comment by tsteuwer** [comment]
We have another internal addon that we're usin gin our app that includes that uses 0.7.15.

**Comment by webark** [comment]
@tsteuwer ya, It looks like that change was made brought in for 0.7.16.  So you might want to see if you can upgrade for that internal addon.

**Comment by bcardarella** [comment]
We are seeing this deprecation warning despite being on the latest Ember (2.12) and latest ember-concurrency (0.8.1). I've heard several times from several sources that the polyfill shouldn't warn if you don't need it, in reality I have never seen this happen. It *always* warns even if isn't necessary. 

Considering that 2.12 will be an LTS that means we are three LTS releases beyond when Owner was introduced. That's a year and a half. If ember-concurrency is trying to maintain lock-step with Ember, I get that. If not then I would advocate for it to drop the polyfill.

**Comment by bcardarella** [comment]
btw, it appears from the polyfill code the conditional warning takes place for the addon during build time. The run-time warning is always happening: https://github.com/rwjblue/ember-getowner-polyfill/blob/master/addon/index.js

**Comment by leepfrog** [comment]
I saw the same behavior too, but traced it back to a few out of date addons (ember-route-action-helpers, ember-moment, etc..). 

After updating those, seems to be fine w/ EC 0.8.1
