### ISSUE TITLE
Accept dom element in waitForEvent

### ISSUE THREAD

**Issue by kellyselden** [machty/ember-concurrency#130]
It would be nice for the case of `waitForEvent(this.element, 'foo')` instead of `waitForEvent(this.$(), 'foo')`.

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

For posterity: Support for this was implemented in ember-concurrency 0.8.13 w/ PR #187
