### ISSUE TITLE
isRunning and Ember Model saves

### ISSUE THREAD

**Issue by gte451f** [machty/ember-concurrency#155]
I'm have a hard time getting a button to work with an E-C task's isRunning property while processing basic model.save() requests.  I've tried moving the save operation around from Component to Route, here is an example that I could use some help with.

Should this work or am I approaching this wrong?

```html
      <!-- myComponent/template.hbs -->
      <button class="btn btn-primary" {{action (perform testAjax model)}}>
        {{#if testAjax.isRunning}}
          {{fa-icon "spinner" spin=true}}
        {{else}}
          Submit
        {{/if}}
      </button>
```

```javascript
// myComponent/component.js
// also fails when this function is passed in from the route/controller
testAjax: task(function* (model) {
  yield model.validate().then(() => {
    if (model.get("isValid")) {
      model.save().then(() => {
        // TBD
      })
    } else {
      // error message here
    }
  });
}).drop()
```

**Comment by machty** [comment]
This might be a better question for the `#e-concurrency` Slack channel on the [Ember Community Slack](embercommunity.slack.com).

**Comment by gte451f** [comment]
Will do, closing issue.
