### ISSUE TITLE
Refresh with nested route only refreshes internal route

### ISSUE THREAD

**Issue by vmalloc** [machty/ember-concurrency#158]
I have two nested routes, where the outer one extends a mixin called *polling route*:

```
import Ember from "ember";
import { task, timeout } from "ember-concurrency";

export default Ember.Mixin.create({
  INTERVAL_SECONDS: 3,

  refresh_loop: task(function*() {
    let self = this;

    let callback = function() {
      console.log('Refreshing');
      self.refresh();
    };

    for (;;) {
      yield timeout(self.get("INTERVAL_SECONDS") * 1000);
      let pred = self.should_auto_refresh;

      if (pred !== undefined && pred.bind(self)()) {
        Ember.run.once(callback);
      }
    }
  }).on("init"),

});
```

The inner route is a regular route. I expect, with this setup, the outer route to refresh itself every 3 seconds once the user visits it.

What happens in this scenario is that the inner route gets refreshed every 3 seconds, while the outer route does not...

**Comment by sagelliv** [comment]
@vmalloc It is definitely related to what you are expecting `this` to be referring to. Try printing the value of `this` when calling the callback.

**Comment by vmalloc** [comment]
I think I figured out the bug - it was a wrong query being used to fetch the object which failed silently. Turns out not to be an ember-concurrency issue at all. Thanks!
