### ISSUE TITLE
The sinister self-cascade-cancel footgun / megatroll

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#161]
This issue has come up enough times that I figured I'd make an official issue about it so I could amass ideas:

When you have a Component task that performs and yields a task on a Service, and the Service changes the state in such a way that it causes the Component to unrender, then componentTask will be canceled and cascade-cancel serviceTask.

I personally run into this issue all the time because in my mobile app, we use tasks on services to coordinate global state changes to the app, e.g. a button on one page will run a component task, which runs a service task to cause a page transition. If I forgot to "sever" the entanglement between componentTask and serviceTask, then the component gets destroyed, canceling componentTask and serviceTask, and hence any code that is suppose to run on serviceTask after the page transition / re-render will not run.

My hackish solution so far has been to introduce the following util macro in our code base to intentionally stick out like a sore thumb and clarify what's happening:

```
/*
 * ember-concurrency cancels tasks (and recursively cancels
 * any yielded child tasks) when the object a task lives on
 * is destroyed. This is a good default, but is surprising
 * in cases where, say, a component yields a task.perform on
 * a service, and then that component gets unrendered as part
 * of what the service task does. So by wrapping the serviceTask.perform
 * in `goOnWithoutMe`, the component task will still be canceled
 * but the service task will go on even though the component
 * task that called it was canceled.
 **/
export function goOnWithoutMe(taskInstance) {
  return Ember.RSVP.resolve(taskInstance);
}
```

which would be used as follows:

```
componentTask: task(function * () {
  yield goOnWithoutMe(this.get('myService.someTask').perform())
})
```

It already sucks that this hack is required to facilitate an otherwise nice pattern, but there are even more problems:

- it's really hard to explain when and why you'd need this hack; when this gotcha bites, things just seem to stop working part way through with no messaging or obvious explanation as to why
- while the promise-wrapping fixes the problem of undesirable-implicit-cancels-upon-destruction, it means explicit cancels that you _would_ expect to cancel `serviceTask` will not actually cancel `serviceTask` since promises aren't cancelable.

So, we need a solution to this problem. I've proposed an `.atomic()` task modifier in other related issues; you specify a serviceTask as `atomic()` which would prevent it from canceling partway through, but again, you'd have to know in advance that you need this modifier, and if you forget it, you get the Silent Treatment.

**Comment by joukevandermaas** [comment]
We had a short slack conversation about this, but I figured I'd copy/paste some stuff in here for posterity :smile:. We have a similar scenario in our app, using two components.

Basically we have something like this:

```
<!-- some-component.hbs -->

{{#if (not myTask.isRunning)}}
  {{#fancy-button onClick=(perform myTask)}}
    Do the thing
  {{/fancy-button}}
{{/if}}
```

Where `fancy-button` has its own task to handle a click:

```
// fancy-button.js

clickHandler: task(function*() {
  yield this.get('onClick')();
});
```

This does produce the warning when run:

> ember-concurrency detected a potentially hazardous "self-cancel loop" between parent task `passedAction` and child task `submit`. If you want child task `submit` to be canceled when parent task `passedAction` is canceled, please change `.perform()` to `.linked().perform()`. If you want child task `submit` to keep running after parent task `passedAction` is canceled, change it to `.unlinked().perform()`

I see no opportunity to do `.unlinked()`, because the task is passed in from the template and `this.get('onClick')` in `fancy-button` returns a closure.

**Comment by machty** [comment]
@joukevandermaas so in the spirit of not building too much functionality up front until we can feel out the pain points, one solution that I think would work is to provide a parallel unlinked handle to the task, e.g.

```js
  foo: task(function * () {
  }),

  unlinkedFoo: computed(function () {
    return this.get('foo').unlinked();
  }),
```

and then you'd pass `(perform unlinkedFoo)` to the component instead.

You can also encapsulate this as such:

```
function unlinkedTask(taskName) {
  return computed(function () {
    return this.get(taskName).unlinked();
  }),
}

// ...

  foo: task(function * () {
  }),
  unlinkedFoo: unlinkedTask('foo'),
````

I won't be surprised if we address this in a future API with something less hacky/boilerplate, perhaps something like `(perform wat linked=false)`.

**Comment by machty** [comment]
Hmm this approach will only work for `unlinked`... if you try and provide a `linked()` variant to get around the footgun warning then you run the risk of evaluating the CP getter whilst not in a task. Maybe I need to change #167 so that `.linked()` only tries to link when `.perform()`ed?
