### ISSUE TITLE
New module imports are broken in 0.8.8 on older apps

### ISSUE THREAD

**Issue by gmurphey** [machty/ember-concurrency#176]
Our consuming app pulled in 0.8.8 this morning and we're now seeing issues within our apps and tests (our app is running on ember@~2.9 and ember-cli-babel@^5).

```
Could not find module `@ember/component/helper` imported from `dummy/helpers/perform`
```

Seems like it could be fixed by #171. We've fixed this by locking our ember-concurrency version to 0.8.7 for now.

**Comment by machty** [comment]
blarg my bad, I totally forgot about that PR. Merging that, and if tests are green I'll push 0.8.9 and maybe yank 0.8.8

**Comment by machty** [comment]
@gmurphey can you try 0.8.9?

**Comment by gmurphey** [comment]
The build is green again! :tada:

@machty Thanks for releasing so quickly, and thanks so much for ember-concurrency!
