### ISSUE TITLE
reports of potential JIT bugs with Edge 13.10586

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#177]
Reported by @wytlytningnz, getting lots of `You attempted to schedule an action in a queue (undefined) that doesn't exist` which seem to be coming from [here](https://github.com/machty/ember-concurrency/blob/master/addon/-task-instance.js#L645)

**Comment by wytlytningNZ** [comment]
I am seeing it on Microsoft Edge 13.10586 on Windows 10.
For reference it seems like others have [experienced similar behaviour](https://github.com/emberjs/ember.js/issues/12915#issuecomment-212530677)

**Comment by machty** [comment]
I believe this issue is fixed but will wait and see; SauceLabs has Windows 10 Edge 13.10586, and I was able to reproduce the issue on the ember-concurrency.com website, which was still on 0.8.7.

Here's a video of the reproduction and the fix: https://www.youtube.com/watch?v=781u5O1Hisg&feature=youtu.be

It's tricky to test because:

1) Opening Edge dev tools disables JIT (i think)
2) If you want to directly test against the e-c repo you have to build/rebuild with full minification, etc

But I think the bug has probably been eliminated, but I'll leave this issue open for folk to confirm that they're no longer seeing bug reports from Edge browsers.

**Comment by wytlytningNZ** [comment]
@machty I have confirmed in production that this issue is no longer present for me (Windows 10 Edge 13.10586)

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

Given that this issue is 1) almost two years old and 2) the browser at-hand now uses a totally different engine, I'm going to assume it's safe to close this 😉
