### ISSUE TITLE
Ember.computed task.isRunning == "You modified isRunning twice in a single render"

### ISSUE THREAD

**Issue by davelindquist-egistix** [machty/ember-concurrency#179]
[double-render-bug-js-and-hbs.zip](https://github.com/machty/ember-concurrency/files/1258324/double-render-bug-js-and-hbs.zip)
I'm encountering a "You've modified xxx twice in a single render" error when using ember-concurrency tasks inside computed properties.

Here's an extremely minimal example of a component that demonstrates the problem:

**double-render-bug.js**:

    import Ember from 'ember';
    import { task, timeout } from 'ember-concurrency';

    export default Ember.Component.extend({
    	task: task(function * () {
    		yield timeout(1000);
    		return 'done';
    	}),
    	taskInstance: Ember.computed(function() {
    		return this.get('task').perform();
    	}),
    	resultValue: Ember.computed.alias('taskInstance.value'),
    	isRunning: Ember.computed.alias('task.isRunning'),
    });

**double-render-bug.hbs**:

    {{isRunning}} / {{resultValue}}

It appears that what happens is:

1. The getter for <code>isRunning</code> is fired, and ember-concurrency returns 'false', since no task instance has yet been created.
2. Then the getter for <code>resultValue</code> is fired, which in turn causes the task to be performed.  Internally, ember-concurrency then sets the 'isRunning' value to <code>true</code>, which in turn causes my <code>Ember.computed.alias</code> to be re-evaluated.
3. Everything blows up, since the <code>isRunning</code> is being "modified twice".

Taking a look at the code, it appears that the <code>isRunning</code> is computed from <code>numRunning</code>, which implies that the <code>numRunning</code> is somehow changing?  Since it is initialized to zero, I can't quite see that...

Or is the problem that the task is not 'created' until after the first get of <code>isRunning</code>?

(I've attached the component js and hbs inside a zip.)

**Comment by davelindquist-egistix** [comment]
For reference, here's a version of the problem that is pure ember -- no ember-concurrency library usages:


    import Ember from 'ember';
    
    export default Ember.Component.extend({
    	task: Ember.Object.extend({
    		isRunning: Ember.computed.gt('numRunning',0),
    		numRunning: 0
    	}).create(),
    	taskInstance: Ember.computed(function() {
    		this.get('task').incrementProperty('numRunning');
    		return Ember.Object.create({value: 'done'});
    	}),
    	resultValue: Ember.computed.alias('taskInstance.value'),
    	isRunning: Ember.computed.alias('task.isRunning'),
    });

**Comment by davelindquist-egistix** [comment]
OK, so I've determined the root cause and a workaround here -- see the [EmberJS Discussion Thread](https://discuss.emberjs.com/t/ember-computed-task-isrunning-you-modified-isrunning-twice-in-a-single-render-solved/13529/11) for full details.

Basically, the problem is:
* The task INSTANCE is responsible for SETTING the isRunning flag (indirectly, as a computed property).
* But we read that value from the TASK, not the task instance.

This means that Ember (correctly) determines that it can compute the isRunning flag first (before the task starts), since we haven't declared the 'taskInstance' as a dependency, and THEN starts the task (which changes the isRunning flag).

The solution is modifying my declaration from:

        isRunning: Ember.computed.reads('task.isRunning')
to:

        isRunning: Ember.computed('taskInstance','task.isRunning',function() {
            this.get('taskInstance'); // If you don't "get" a property that you declared in your deps, it won't really be a dep.
            return this.get('task.isRunning');
        })

This properly declares the dependency, and thus solves the problem (at least for now).

Perhaps it would be a good idea for ember-concurrency to expose an 'isRunning' from the task instance itself?

**Comment by machty** [comment]
EC already exposes an `isRunning` property on TaskInstances: http://ember-concurrency.com/api/TaskInstance.html#isRunning

It's a useful property to have on both Task and TaskInstance depending on your needs.

It sounds like the root issue here is another case of https://github.com/machty/ember-concurrency/issues/136#issuecomment-326826582

**Comment by davelindquist-egistix** [comment]
Ah, thanks for the link!

I was looking for that sort of thing in the documentation at:

[https://ember-concurrency.com/#/docs/derived-state](https://ember-concurrency.com/#/docs/derived-state
)

but didn't find it there.

Anyway, use of that property solves my problem completely -- thanks!

(Oh, and yes, this sounds exactly like #136 -- for some reason I missed that when posting this.)

Thanks!
