### ISSUE TITLE
race: incompatible with waitForEvent

### ISSUE THREAD

**Issue by buschtoens** [machty/ember-concurrency#181]
The `race` helper (and I would guess `all`, `allSettled`, `hash` as well) aren't compatible with / aware of `waitForEvent` (and possibly `waitForQueue`).

It immediately resolves with the `Yieldable` itself.

```js
const $image = $(image);
const maybeError = yield race([
  waitForEvent($image, 'load'),
  waitForEvent($image, 'error')
]);
if (maybeError instanceof Error) throw maybeError;

console.log(maybeError); // => WaitForEventYieldable {object: jQuery.fn.init(1), eventName: "load"}
```

**Comment by ef4** [comment]
@machty this is the issue I mentioned to you last night. The cancellation-aware `race` doesn't have any support for `yieldableSymbol`, so racing between multiple events doesn't work.
