### ISSUE TITLE
Promise helpers should throw a TypeError, if they receive the wrong data structure

### ISSUE THREAD

**Issue by buschtoens** [machty/ember-concurrency#182]
It is so _insidiously_ easy to forget `[]` when using `all()`. :smiling_imp: 

I've just spent 20 minutes debugging this piece of code:

```js
yield all(
  this.verifyAddress(),
  this.verifyAge()
);
```

Can we please add proper type checks for these helper methods? I'm up for a PR!

**Comment by maxfierke** [comment]
Hi @buschtoens 👋 ! I'm going through the issue queue and hoping to close out any PRs that are stale. I know this is almost 2 years old, but are you still up for a PR on this one?
