### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by hadiwina** [machty/ember-concurrency#184]
Hello! I've looked around but I may have missed it, but is there any documentation on upgrading into latest version of Ember Concurrency? List of breaking change, what to look for, etc?

**Comment by buschtoens** [comment]
Did you encounter problems after an e-c upgrade? Personally, I can't remember a breaking change so far, but since e-c is sill `0.x` this could very well be the case.

From what version do you try to upgrade?

There's the [releases list](https://github.com/machty/ember-concurrency/releases).

**Comment by machty** [comment]
This might be helpful too https://github.com/machty/ember-concurrency/blob/master/CHANGELOG.md

**Comment by hadiwina** [comment]
@buschtoens Was trying to get to the latest one. Our app is rather large and have EC used in many places, just wanted to be diligent as to making sure we go through the list. Thanks for the list! 😄 

@machty This definitely helps. Thanks a lot! 👍 

Closing this!
