### ISSUE TITLE
use ember-lifeline for dummy app?

### ISSUE THREAD

**Issue by snewcomer** [machty/ember-concurrency#198]
What do you think about using ember-lifeline for the dummy app?  Specifically, any `while` loop or polling task will cause a test to hang with the test helper so the `pollTask` helper would be quite nice.

Another option is just to [add](https://github.com/machty/ember-concurrency/pull/194/commits/0a7ebe711142e2c2c67d06e7c135b9a743d9c9e8) `!Ember.testing` guards, but I wasn't sure if anybody saw an expanded use case for `ember-lifeline` in this repo.

https://github.com/rwjblue/ember-lifeline

Ref #194

**Comment by machty** [comment]
I reference this issue [here](https://github.com/machty/ember-concurrency/pull/194#issuecomment-358725620)
