### ISSUE TITLE
Replace all `/app` code with re-exports from `/addon`

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#200]
Instead of having helpers/initializers directly implemented via files in `/app`, all of their code should move to `/addon`, and the files in `/app` should simply do `export from` statements ([example](and we shouldn't shy away from these ergo improvements)).

This is a nice convention that most addons adopt that makes it easier to override/extend addon behavior, but would also let us avoid the problem where the `app/` tree can't adopt the new `@ember` import conventions without breaking people's builds due to older versions of ember-cli.

**Comment by corrspt** [comment]
Looking at the merged PR, should this issue be closed?

**Comment by machty** [comment]
Yup :)
