### ISSUE TITLE
Route and Controller unit tests giving runloop error when there is a task in their inits

### ISSUE THREAD

**Issue by danwenzel** [machty/ember-concurrency#202]
When a route or controller performs an ember-concurrency task on init(), their unit tests fail with:

```
Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun.
You will need to wrap any code with asynchronous side-effects in a run
```

This can be fixed by wrapping the test in an `Ember.run`, but I wouldn't expect this to be necessary, as ember-concurrency should already be using the Ember run loop.

I made a simple ember-twiddle that demonstrates the issue: https://ember-twiddle.com/5fdb6f48db88cb9a342f6c1683f7b9a3

**Comment by machty** [comment]
Thanks for the excellent ember-twiddle failing test bug report.

I'm not sure you're correct though that you should be able to avoid wrapping your test logic in Ember.run (though I have admittedly fallen behind the times on ember-testing best practices). If I replace your `Task.perform`s with `Ember.run.once` you run into the same autorun assertion ([see here](https://ember-twiddle.com/bde46e554f872947ddc32c3efd920074?openFiles=controllers.my-controller.js%2C)). Of course, you _should_ be able to use run loop scheduling APIs in your controller lifetime hooks, including init, and internally ember-concurrency relies on being able to do this, but there's no way for ember-concurrency to automatically only run inside a run loop. Let me know if I'm misunderstanding something though.

**Comment by danwenzel** [comment]
Interesting...

I was always under the impression that this error indicated a problem with the application code, where code with _non-Ember_ asynchronous side-effects were not properly wrapped in a run.

It seems odd to me that just putting in an `Ember.run.once` would cause the issue.  I can get your latest twiddle to pass by wrapping the `Ember.run.once` in an `Ember.run` 😕

**Comment by machty** [comment]
Yeah, my understanding is that you're kinda lucking out if don't wrap in `.run` and you don't get the assertion, which happens only if your controller is simple and doesn't do any kind of scheduling. I'll ask some ember-testing people to weigh in though.

**Comment by danwenzel** [comment]
Hey @machty - checking in:  Were you able to get any insight from ember-testing folks?

**Comment by machty** [comment]
Ah, I asked and people confirmed my understanding that if your `init` does any run loop scheduling, either directly or indirectly, you'll need to wrap in a `.run`. I don't think there's anything to fix on the e-c side of things here.

**Comment by danwenzel** [comment]
Interesting... fair enough.  Thanks for checking!
