### ISSUE TITLE
After installing the addon, I got `Uncaught ReferenceError: regeneratorRuntime is not defined`

### ISSUE THREAD

**Issue by vsymguysung** [machty/ember-concurrency#21]
I have no idea why I get this error. Any idea?
Below is my environment information. Thanks in advance.

```
 -------------------------------
 Ember      : 2.3.1
 Ember Data : 2.3.3
 jQuery     : 2.1.4
-------------------------------
```

I can reproduce the error with a plain new ember-cli application with only this addon installed.

**Comment by machty** [comment]
Sorry about that; we tried to automate this process but need to take another stab at it to get it right. In the meantime, I upgraded the README docs to include the following:

ember-concurrency also requires that the Regenerator runtime be included in your app. The easiest way to ensure this is to enable the babel.includePolyfill option in your ember-cli-build.js or Brocfile.js files.

```
var app = new EmberAddon(defaults, {
  babel: {
    includePolyfill: true,
  },
});
```

**Comment by vsymguysung** [comment]
@machty  Thanks much!  :+1:

**Comment by jamesarosen** [comment]
In case it helps anyone who comes across this, I ran into this problem in an addon of my own that uses ember-concurrency. The solution is to ensure that it loads after ember-concurrency:
```js
// package.json
"ember-addon": {
  "after": "ember-concurrency",
  "configPath": "tests/dummy/config"
}
```
