### ISSUE TITLE
Ember Concurrency error when refreshing route and using loading templates

### ISSUE THREAD

**Issue by danr1979** [machty/ember-concurrency#222]
Hi.

In my route I have an Ember Concurrency task called "data" that I perform from the model hook as follows:

```javascript
export default Route.extend(AuthenticatedRouteMixin, {
    model(params) {
        return this.get('data').perform(params);
    },

    data: task(function* () {
        try {
            return yield RSVP.hash({
                applications: this.get('store').findAll('application-list'),
                partners: this.get('store').findAll('partner')
            });
        } catch (e) {
            this.get('errorHandler').handleErrors(e);
        }

    }).cancelOn('deactivate').restartable(),

    actions: {
        routeRefresh() {
            this.refresh();
        }
    }
});
```

I also use the Ember convention of a loading template in a loading.hbs file.  The reason I mention this is because if I call the `routeRefresh()` action I get the following error:

`Error while processing route: my.route TaskInstance 'data' was canceled because .cancelAll() was explicitly called on the Task.`

but if I delete the loading.hbs template the route refresh proceeds as normal.

Is this something to do with the fact that loading templates are transitioned to so the current route thinks it has been transitioned away from meaning the Ember Concurrency task is cancelled?

Any help would be appreciated.

Thank you.

**Comment by danr1979** [comment]
Ok, I think I've answered my own question!  I removed the `cancelOn('deactivate')` from the task and it works fine now.

I only used that after reading the section  of the docs about route tasks but hopefully removing it won't have any unexpected side effects?

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

It appears this was resolved, so I'm closing it out.
