### ISSUE TITLE
Ember newsletter mentions evented task modifier but not in docs

### ISSUE THREAD

**Issue by BryanCrotaz** [machty/ember-concurrency#225]
> Ember Concurrency 0.8.18 Released
> Adds .evented() task modifier and task lifecycle events.

But can't find this in docs to see what it does

**Comment by machty** [comment]
They are [here](http://ember-concurrency.com/docs/task-lifecycle-events)

**Comment by BryanCrotaz** [comment]
Not listed here: http://ember-concurrency.com/api/

**Comment by BryanCrotaz** [comment]
or here http://ember-concurrency.com/api/TaskProperty.html

**Comment by maxfierke** [comment]
There was a missing doc tag for the `evented()` call on the `TaskProperty`, but the other docs should be on there for the events and such. (See #228 for the TaskProperty add)

But the reason it's missing from the API docs seems to be that `jsdoc` might just not have been re-run last time the docs site was updated. I'm seeing this in the index page's generation date: `Documentation generated by JSDoc 3.4.0 on Wed Feb 28 2018 11:11:05 GMT-0500 (EST)`

**Comment by maxfierke** [comment]
@BryanCrotaz this is now fixed
