### ISSUE TITLE
Automatically put tasks in debug mode while running in a non production build

### ISSUE THREAD

**Issue by robert-j-webb** [machty/ember-concurrency#239]
Hi,

I saw a video on Ember map about how to put the tasks in debug mode while having issues with Ember Concurrency, and I never knew about that until then. Multiple times I've had issues where Concurrency will stop errors from showing up and it has been frustrating to debug and fix these problems. Is it possible that we can change it so that if the build is development, errors will automatically surface without the need for a `.debug()` call?

**Comment by shawndumas** [comment]
here is the video in question 

















https://embermap.com/video/debugging-ember-concurrency-tasks










|

**Comment by robert-j-webb** [comment]
Ok thank you very much!
