### ISSUE TITLE
EC could play nicer in ES6 classes

### ISSUE THREAD

**Issue by BryanCrotaz** [machty/ember-concurrency#241]
```
export default MyComponent extends Component {
  myTask = task(function * {
    await timeout(1000);
  }
}
```

Runtime deprecation:
```
DEPRECATION: [DEPRECATED] computed property '_debounceAddHistoryStep' was not set
on object '<dummy@component:property-editor::ember346>'
via 'defineProperty' [deprecation id: ember-meta.descriptor-on-object]
```

**Comment by buschtoens** [comment]
You'll surely like [`ember-concurrency-decorators`](https://github.com/machty/ember-concurrency-decorators):

```js
import Component from '@ember/component';
import { restartableTask } from 'ember-concurrency-decorators';

export default class ExampleComponent extends Component {
  @restartableTask
  doStuff = function*() {
    // ...
  }
}
```

With TypeScript you can use even nicer syntax:

```ts
import Component from '@ember/component';
import { restartableTask } from 'ember-concurrency-decorators';

export default class ExampleComponent extends Component {
  @restartableTask
  *doStuff() {
    // ...
  }
}
```

Give it a try with:

```
ember install ember-concurrency-decorators@v0.0.4-beta.0
```

**Comment by BryanCrotaz** [comment]
Works nicely - thanks

**Comment by bartocc** [comment]
I agree that `ember-concurrency-decorators` helps removing this deprecation, but it is much more alpha than `ember-concurrency` itself, and refactoring would also take time.

Is there anything `ember-concurrency` could do in its codebase to avoid this deprecation?

**Comment by buschtoens** [comment]
> Is there anything ember-concurrency could do in its codebase to avoid this deprecation?

Unfortunately, no. This deprecation is triggered, because you are _assigning_ a computed property on an instance. It is not caused by ember-concurrency, but by the consumer using it incorrectly.

You can force the same deprecation with a computed property for example:

```js
import EmberObject, { computed } from '@ember/object';

export default class extends EmberObject {
  someProp = computed(function() {});
}
```

This is the reason ember-decorators exists.

If you want to use ES6 classes (properly), you have to use decorators.

> but it is much more alpha

Not _really_. I should probably just cut a release and ask Alex to remove the EXPERIMENTAL warning from the repo description. I was only holding back because of insufficent test coverage. But tbh I've been using it in production for months and so have been others. It's been great so far. Didn't discover any bugs.

**Comment by BryanCrotaz** [comment]
I've been using it in production for months

Me too. No issues at all.

**Comment by bartocc** [comment]
That's very good news. I'm gonna give e-c-d a try then ;-)

**Comment by allthesignals** [comment]
If you can't use decorators for some reason, you can eliminate the deprecation warning by using `defineProperty`:

```javascript
import { task } from 'ember-concurrency';
import { defineProperty } from '@ember/object';

export default class LabsSearchComponent extends Component {
  constructor() {
    defineProperty(this, 'myTask', task(function*() {  /* stuff */ }));
  }
}
```

FYI `defineProperty` is private, although the [deprecation](https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object) guide uses it.

**Comment by buschtoens** [comment]
FWIW `defineProperty` is a valid solution that works safely, *however* it (and the assignment syntax like `myTask = task(function*() { ... })`) have a subtle problem.

They are run each time the object is instantiated, which degrades performance and increases the memory footprint of your application. Just keep that in mind. 😄
