### ISSUE TITLE
Improve debugging experience

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#25]
- [ ] add ability to log why a task was canceled, displaying the names of the chain of cancelation, the root cause, and the name of the policy (where applicable) that caused the cancelation
- [ ] investigate bringing the visuals/graphs from the docs into the console, via background images, or console.table, or something better than a console.log string

**Comment by JackCA** [comment]
@machty I just discovered this as I was thinking it would be a nice feature. Did you close it based on it being low priority? Or superseded by another issue?
