### ISSUE TITLE
Opt out of last* derived state

### ISSUE THREAD

**Issue by bendemboski** [machty/ember-concurrency#263]
I have a number of service and controller tasks that return very large data structures (blobs, JSZip objects, etc.), which are then processed and discarded. But they are unable to be garbage collected because they are held in memory by the task scheduler's various `last*` properties, and since the tasks are on singletons, the memory can't be freed until the task is run again (and it's replaced with a similarly large data structure).

What I'd really like is a way to opt out of the `last*` derived state on a task-by-task basis, perhaps something like:

```javascript
foo: task(function*() {
  // ...
}).withoutLastState()
```

When [this](https://github.com/machty/ember-concurrency/issues/243) lands it would give me a public mechanism to dump that data, but I'd have to do it at each call site of the task, rather than encapsulating it in the task itself. Currently I don't think there's any way to recover that memory other than some pretty ugly workarounds (or going back to an async function with a bunch of `this.isDestroyed` checks 😦)

If this sounds reasonable and we agree on an API, I'd be happy to PR the changes. I could also write an RFC if more clarification/formal discussion is needed.

**Comment by machty** [comment]
I am interested in implementing this.

**Comment by bendemboski** [comment]
Hey @maxfierke I think this specific request has been addressed by the `onState()` task modifier (although I haven't been able to find any documentation for it).

Personally, I never want the task state and don't want the extra memory it consumes (which is a lot for me since I process large data blobs and the like in tasks), so would love a way to opt out globally (and then maybe opt back in for specific cases), but for now I'm surviving by calling this gem from `app.js`:

```javascript
import { TaskFactory } from 'ember-concurrency/-private/task-factory';

export default function hackEcTask() {
  let createTask = TaskFactory.prototype.createTask;
  TaskFactory.prototype.createTask = function () {
    this.setOnState(null);
    return createTask.call(this, ...arguments);
  };
}
```

**Comment by maxfierke** [comment]
Still thinking through considerations for making `TaskFactory` a public API, but for now, `onState` is here to stay, at least, but you're right, lacks documentation. Will work on that. should theoretically work on a per-task basis too, e.g. `@task({ onState: null })`

**Comment by maxfierke** [comment]
`onState` is now documented as a modifier to the decorator: https://ember-concurrency.com/api/global.html#task.

As an aside, I'm working on an RFC to make `TaskFactory` a public API as well, and will do some thinking about setting defaults.

**Comment by bendemboski** [comment]
Thanks @maxfierke!

**Comment by machty** [comment]
Would be interesting to see a perf comparison between a vanilla task and and a null-onState task if anyone feels like making a benchmark :)

**Comment by bendemboski** [comment]
@machty for me it's about memory consumption -- I have tasks that fetch very large files, load them into JSZip objects, and return them as their result. The application extracts data from them and then discards the JSZip objects, so the fact that the derived state keeps a reference to the result of the last task instance (as well as the arguments I think) pins very large data objects in memory. It's a fairly specific use case, but adds up to a lot of unnecessary memory consumption in my app.

That's why ideally I'd have the ability to keep the `isRunning` and all that, but not hold only to any _values_ (arguments/return values), which I think requires not holding onto any task instances because their scopes often hold references to values.
