### ISSUE TITLE
Typings?

### ISSUE THREAD

**Issue by gossi** [machty/ember-concurrency#269]
For those of us using typescript, typings would improve autocompletion for our IDEs a lot. But I'm also sure, many people have some private types already done. It's time to throw them together.

That would maybe also mean some restructuring to be more clear? Because at the moment I do this:

```
import { Task } from 'ember-concurrency/-task-property';
```

which not only doesn't exist but also feels like the wrong import. I'd prefer something like this:

```
import Task from 'ember-concurrency/task';
```

which seems more about right - just saying.

**Comment by buschtoens** [comment]
There's already a lot of back and forth going on in https://github.com/machty/ember-concurrency/pull/209 😜

**Comment by gossi** [comment]
Erf, my search only showed results from issues, not pull requests. I'm closing this one in favor of the PR.
