### ISSUE TITLE
Task properties broken in canary

### ISSUE THREAD

**Issue by bendemboski** [machty/ember-concurrency#279]
[this](https://github.com/emberjs/ember.js/commit/1c72067eccef15c294c9d55d66e18241f4336a11#diff-aa29907c3a02fdab7b969fbf67e81c62R163) commit changes the signature of `ComputedProperty`'s constructor to accept an array, so [this](https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L419) passes the wrong arguments and throws a `TypeError: Found non-callable @@iterator` exception (although for some reason in CI I saw `Assertion Failed: A computed property key must be a string, you passed undefined undefined` instead).

I'm happy to take a crack at a PR to fix this, but I'm unsure of how. I'll leave a comment in that commit asking the core folks if they have a recommendation, but the only two options I can think of are:

1. Base it an Ember version check (we'd want to verify that this will be released in Ember 3.8 first)
2. Use `try...catch` to invoke it one way, and on failure, try to invoke it the other way (seems pretty sketchy).

Other ideas?

**Comment by pzuraq** [comment]
See https://github.com/machty/ember-concurrency/pull/277

**Comment by pzuraq** [comment]
Also, for how to be compatible with multiple versions at once, we should use [ember-compatibility-helpers](https://github.com/pzuraq/ember-compatibility-helpers), since it checks the Ember version at build time which allows us to completely strip out the unused version for folks who aren't using that version.

**Comment by bendemboski** [comment]
Oh, nice, already in progress! Great, thanks for being so diligent and sorry for the extra noise!

**Comment by pzuraq** [comment]
All good, private API changes like this are always a little tricky, and it's good to know when it's affecting people and for visibility in general 😄

**Comment by balinterdi** [comment]
Unfortunately I get this very error (`TypeError: Found non-callable @@iterator`) using ember-concurrency 0.9.0 and Ember Octane (which is a quite recent "canary" version).

It originates from this line in `ember-animated`:
https://github.com/ember-animation/ember-animated/blob/master/addon/components/animated-orphans.js#L91

and fails on this line:
https://github.com/emberjs/ember.js/blob/5e4b58feee/packages/%40ember/-internals/metal/lib/computed.ts#L207

It has worked fine on Ember 3.8 (but that's probably not much help).

**Comment by lypborges** [comment]
@balinterdi I just run
```
rm yarn.lock 
rm -rf node_modules 
yarn install
``` 
and fix the problem.
