### ISSUE TITLE
Incompatible with Ember 3.9

### ISSUE THREAD

**Issue by alexlafroscia** [machty/ember-concurrency#280]
I'm seeing some test failures in one of my addons running against `ember-beta`

https://travis-ci.com/alexlafroscia/ember-rx/jobs/179065658

Ultimately, this error is stemming from `ember-concurrency` and (presumably) `task` not being compatible with the changes that were made to the Computed Property system in Ember 3.9 to gain compatibility with decorators.

While not obvious in CI, the error that I'm seeing is actually this:

> TypeError: Found non-callable @@iterator

Which stems from calling the constructor of `ComputedProperty` with a function here

https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L419-L431

The constructor now expects an array as the first argument

https://github.com/emberjs/ember.js/blob/89b122ac65824b48d7c08da7f2d8b3998041c372/packages/%40ember/-internals/metal/lib/computed.ts#L168

The error I'm seeing is specifically triggered because of the way that first argument is "spread" here

https://github.com/emberjs/ember.js/blob/89b122ac65824b48d7c08da7f2d8b3998041c372/packages/%40ember/-internals/metal/lib/computed.ts#L207

**Comment by alexlafroscia** [comment]
I see that #277 is open to address the incompatibility here -- hopefully that'll land soon since addon authors running against `ember-beta` are going to start getting bitten by this now!

**Comment by machty** [comment]
Should be fixed in 0.9.0

**Comment by edeis53** [comment]
Can we reopen? I'm upgrading our app to Ember 3.10.1 and Ember concurrency 1.0.0, and we're getting the `Uncaught TypeError: Found non-callable @@iterator`

We are declaring our tasks using the following syntax:
```
  demoTask: task(function*() {
    yield timeout(400);
    this.doFoo();
  }),
```

Do we need to switch over to new ember syntax and decorators?

```
metal.js:2877 Uncaught TypeError: Found non-callable @@iterator
    at new ComputedProperty (metal.js:2877)
    at new TaskProperty (-task-property.js:398)
    at task (index.js:58)
    at Module.callback (base-component.js:23)
```

**Comment by edeis53** [comment]
Oops. Ignore that one, I was premature. We were also using ember-concurrency-scroll addon, which uses 0.8 and was clobbering the 1.0 dependancy in our app.

**Comment by basz** [comment]
Hi, I'm seeing the same error. For ember 3.11.0 and e-c 1.0.0. Shouldn't 1.0.0 resolve this issue?

> Do we need to switch over to new ember syntax and decorators?

If switching format helps I can do that, but to what format would I need to switch? An example would be appreciated...

**Comment by maxfierke** [comment]
@basz You should ensure you don't have a dependency that is resolving to a lower version of ember-concurrency (e.g. ember-power-select, etc.). If there's not a more recent version of the addon that permits ember-concurrency 1.0.0, you can use Yarn resolutions to force it to resolve to ember-concurrency 1.0.0 (if you're using Yarn).

**Comment by basz** [comment]
@maxfierke aahhh... now my apps works again! (or, well, I can continue to kill other upgrade bugs...) but,  very helpful and wasn't aware of this meganism...
