### ISSUE TITLE
waitForProperty never yielded when used when @tracked property changes

### ISSUE THREAD

**Issue by trek** [machty/ember-concurrency#292]
I'm not entirely sure if this is an e-c bug or an issue with Octane Edition, but combining `waitForProperty` with a `@tracked` property doesn't work.

```
export default class SomeService extends Service {
  @tracked someProperty = false;

  @task(function *() {
    yield waitForProperty(this, 'someProperty');

    // this code is unreached even if `someProperty`
    // becomes true.
  }) aTaskThatWaits  
}
```

This appears to be caused by the various `waitFor{*}`s being based on [addObserver](https://github.com/machty/ember-concurrency/blob/d6b30e8b55c18b1e3da97d880c7ef612a5168aab/addon/-wait-for.js#L96).

Although I'd assume backwards interop at the `EmberObject` level to not break SemVer in Ember.js itself.

**Comment by rwjblue** [comment]
@trek The [tracked properties RFC has specific text](https://emberjs.github.io/rfcs/0410-tracked-properties.html#observers) RE: interop with observers:

> Observers use a fundamentally different system for tracking changes than tracked properties, but this does not mean that it is impossible for the two systems to interoperate, and it theory it shouldn't require much effort to maintain such interoperation or regress performance in any meaningful way.
> 
> As such, tracked properties will be made to interoperate with observers so that whenever a tracked property is set using any valid syntax, observers watching that key will be fired:
> 
> ```js
> import { tracked } from '@glimmer/tracking';
> import { addObserver } from '@ember/object/observers';
> 
> class Person {
>   constructor() {
>     addObserver('firstName', () => {
>       console.log('firstName changed!');
>     });
>   }
> 
>   @tracked firstName;
> }
> ```
>
> If in the implementation of this RFC it becomes apparent that there are major caveats to supporting interop with observers, a followup RFC will be made to address those caveats and make a decision on whether or not to support observers with those additional constraints.

**Comment by andrewfan** [comment]
@trek @rwjblue @maxfierke I got the same error and found that it happens because 
https://github.com/machty/ember-concurrency/blob/d6b30e8b55c18b1e3da97d880c7ef612a5168aab/addon/-wait-for.js#L96
here we are trying to call missing `addObserver` / `removeObserver` methods 
If I add those 2 missing methods everything works fine with @tracked 
@trek 
``` 
import { addObserver, removeObserver } from '@ember/object/observers';

export default class SomeService extends Service {
  @tracked someProperty = false;

  addObserver() {
    addObserver(this, ...arguments);
  }

  removeObserver() {
    removeObserver(this, ...arguments);
  }

  @task(function *() {
    yield waitForProperty(this, 'someProperty');

    // this code is unreached even if `someProperty`
    // becomes true.
  }) aTaskThatWaits  
}
```
So I believe the same trick can be done in e-c source

**Comment by DuBistKomisch** [comment]
Note to anyone else who runs into this problem: you really have to use `set` explicitly like the test added in the PR, and listen to the `@tracked` property. I can't find any way to make it work with listening to getters directly, you just need to manually access them in the callback. Adding `@dependentKeyCompat` should work in theory but it's unreliable in my testing.

**Comment by Techn1x** [comment]
> Note to anyone else who runs into this problem: you really have to use set explicitly like the test added in the PR, and listen to the @tracked property. I can't find any way to make it work with listening to getters directly

I have had similar troubles, trying to wait for a getter to an ember-data attribute on a model. It could be because the model is currently using the `@classic` decorator. Either way, it shows this `waitForProperty` method doesn't work in all cases.

> you just need to manually access them in the callback. 

Thanks, this helped fix my issue. Now accessing the ember-model attribute directly, instead of the getter to it, and this seems to work & update now.

**Comment by Herriau** [comment]
Similarly I have found `waitForProperty()` to be unreliable for observing state derived from `@tracked` properties. It seems however that this isn't an issue with EC itself but rather with Ember's `addObserver()`. We are refactoring away from using EC as much as possible as a result, which is quite a shame as we had some good patterns going.
