### ISSUE TITLE
Consider console error if an exception happens

### ISSUE THREAD

**Issue by amk221** [machty/ember-concurrency#295]
I'm new to ember concurrency, and I found it odd that if I don't manually try/catch an error it will be 'lost', or, I won't know about it when a task is run.

Perhaps there could be a console warning to notify in development mode that something has gone awry.

**Comment by maxfierke** [comment]
Hi @amk221! Generally if you do not handle an error in an ember concurrency task, it should bubble to `RSVP.onerror` or `Ember.onerror` and be visible on the browser console.

Can you provide some details on what Ember version and ember-concurrency version you are using? Are you using any error reporting add-ons that might be overriding these handlers?

**Comment by amk221** [comment]
👋🏻 I am responding to both those things (for sentry), so I’ll check if
there is a miss configuration and get back to you, with a demo repo if
necessary. Thanks!

**Comment by amk221** [comment]
Thanks, was a miss use of `allSettled` on my part.
