### ISSUE TITLE
task abruptly ends when saving a model after changing attribute named 'state'

### ISSUE THREAD

**Issue by nickdoccheer** [machty/ember-concurrency#296]
Saving a attribute named "state" in a model causes the task to not finish:
```
hello: task(function*(){
      console.log("here1")
      yield this.model.set('state', 'inactive');
      yield this.model.save()
      console.log("here2")
  }).drop()
```
The save works fine, but "here2" never gets printed. 

 ```
hello: task(function*(){
      console.log("here1")
      yield this.model.set('hello', 'world');
      yield this.model.save()
      console.log("here2")
  }).drop()
```
In this case, the save works fine and the server returns the "state" attribute and  "here2" gets printed.

**Comment by machty** [comment]
I'm not sure but I think `state` might be a reserved property on Ember Data models that you're not allowed to modify. I'm guessing it's throwing an exception when it gets to that line.

**Comment by nickdoccheer** [comment]
In ember data, they use `state` in their tests so I don't think it is reserved. https://github.com/emberjs/data/blob/178d37aa0ab6edd4e37a9a4f84165f7837ddb3e2/packages/-ember-data/tests/integration/snapshot-test.js#L40

I did put it in a try catch initially (like below) and it would still only print "here1".
```
hello: task(function*(){
  try{
     console.log("here1")
     yield this.model.set('hello', 'world');
     yield this.model.save()
     console.log("here2")
  }catch(e){
     console.log("here3")
 }).drop()
```

This may just be an edge case but I wanted to notate this in case anyone else runs into it.

Appreciate the response, and thanks for creating this add-on!

**Comment by nickdoccheer** [comment]
This was a red herring, it was not the name of the attribute.  Turns out that if some computed property is watching the attribute that is being changed, the task ends abruptly.  Still not sure why but closing this issue.
