### ISSUE TITLE
`perform` helper doesn't work with `pipe` helper

### ISSUE THREAD

**Issue by knownasilya** [machty/ember-concurrency#307]
The pipe helper (https://github.com/DockYard/ember-composable-helpers#pipe) works on actions that return promises, unfortunately the `perform` helper returns the result of `bind` from the runloop and this causes subtle bugs. If the perform helper could return the TaskInstance instead, it would work well with the `pipe` helper.

**Comment by machty** [comment]
What if you just passed the task directly to pipe? (Alternatively you can use the `(task myTask 1 2 3)` helper to curry args into the task, similar to the `(action)` helper.) I don't know how `pipe` works internally but if it uses the `INVOKE` symbol to find invocable actions, it might Just Work™

**Comment by knownasilya** [comment]
As far as I can tell it doesn't use `INVOKE`. I'll try passing the task.

**Comment by machty** [comment]
Is there something e-c could be doing different here? If not, this might be more of a `pipe` issue

**Comment by knownasilya** [comment]
It would just work if `bind` was removed (https://github.com/machty/ember-concurrency/blob/master/addon/-helpers.js#L9). Not sure that it's needed any more.

**Comment by maxfierke** [comment]
@knownasilya could you expand more on what you mean by subtle bugs, or perhaps provide a reproducible test case to illustrate the behavior?

I tried removing the `bind` and it had the same characteristics either way, where: `pipe` executes the `perform`, receives a `TaskInstance` which it then treats as a Promise, and executes the next action afterwards as I'd expect.

**Comment by knownasilya** [comment]
Maybe that was a red herring all along. This is the issue it seems:

```js
  @task
  addWork = function*() {
    let work = yield this.apollo.mutate(
      {
        mutation: addWork,
        variables: {
          url: this.workUrl
        }
      },
      'createWork'
    );

    this.close();
  };
```

Where the `close` removes that component from the DOM. Which returns `Error: TaskInstance 'addWork' was canceled because the object it lives on was destroyed or unrendered. For more information, see: http://ember-concurrency.com/docs/task-cancelation-help`

**Comment by knownasilya** [comment]
@maxfierke how would you handle the close? Could tasks have a `return () => this.close()` that runs outside the task?

**Comment by maxfierke** [comment]
@knownasilya I personally would take it as a signal to move the task up a level in the component hierarchy, but know this might not always make sense. In that case, I would probably do something like `next(() => this.close());` with `next` from `@ember/runloop`, which I know people often do (or `later(..., 1);`, but that's equivalent). Could also use the `timeout` or `rawTimeout` helpers as promises to do `timeout(1).then(() => this.close());`.

Returning some sort of post-completion callback would be difficult without having a way to differentiate that from tasks that simply return a function as their end value. something like how goroutines works would be kind of interesting though, e.g. `yield go(() => this.close());` and have it get added as a finalizer.
