### ISSUE TITLE
Uncaught Error: Assertion Failed: A computed property key must be a string, you passed undefined undefined

### ISSUE THREAD

**Issue by erichonkanen** [machty/ember-concurrency#323]
I'm receiving this error after upgrading and unsure how to resolve it.
```
ember 3.11.1
ember-cli-babel 7.12.0
ember-concurrency 1.1.0
```
```
Uncaught Error: Assertion Failed: A computed property key must be a string,
you passed undefined undefined
```
I've tried different ways of writing the task based on comments in https://github.com/machty/ember-concurrency/issues/283, but I keep getting same error.

code:
```
  @(task(function* (queryString, options, Client=CrossStorageClient) {
      ...
  }))
  _connect;
```

**Comment by maxfierke** [comment]
@erichonkanen Hi Eric, could you post a bit more context about where you're using the task? Is it on a "classic" Ember Component?  A Glimmer component? EmberObject/Service? ES native class, etc.? Could you share the code that's inside the task?

**Comment by erichonkanen** [comment]
hey @maxfierke, just went through the steps of upgrading again and ended up in the same place
- ember 3.10.2
- EC 1.0.0
- ECD 1.0.0

app/services/storage.js
```
import Service, { inject as service } from '@ember/service';
import { task } from 'ember-concurrency-decorators';

export default class StorageService extends Service {
  @service ajax;

  connect(queryString) {
    return this._connect.perform(queryString, { timeout: this.TIMEOUT });
  }

  @task
  _connect = function* (queryString, options, Client=CrossStorageClient) {
    const params = new URLSearchParams(queryString);
    const hubUrl = params.get('hub_url');
```
The service is initialized through the application route:
```
import ApplicationRouteMixin
  from 'ember-simple-auth/mixins/application-route-mixin';
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class ApplicationRoute extends Route.extend(
    ApplicationRouteMixin) {
  @service storage;

  beforeModel() {
    return this.storage.connect(window.location.search);
  }
```

**Comment by erichonkanen** [comment]
so, turns out after I ran `npm list ember-concurrency`, I noticed that `ember-power-select` was using an older version, which for some reason was being used and causing the error! oy!
```
npm list ember-concurrency
lift-experience-builder@ /Users/eric/Projects/acquia/lift-experience-builder
├── ember-concurrency@1.0.0
├─┬ ember-power-calendar@0.13.3
│ └── ember-concurrency@1.0.0  deduped
└─┬ ember-power-select@2.2.2
  └── ember-concurrency@0.8.27
```

**Comment by buschtoens** [comment]
[`ember-cli-dependency-lint`](https://github.com/salsify/ember-cli-dependency-lint) can guard against this.

**Comment by erichonkanen** [comment]
@buschtoens thank you, hadn't used that before but seems very helpful!
