### ISSUE TITLE
Link to es6 transpilation article returns 404

### ISSUE THREAD

**Issue by SYU15** [machty/ember-concurrency#328]
https://github.com/machty/ember-concurrency/blob/af891b292428ad4a789c1e172a1293119d42f4d9/tests/dummy/app/docs/testing-debugging/template.hbs#L114

Is the content in that article still relevant? I was trying to search for a live link but couldn't find one. If it doesn't exist anymore, is there an equivalent article that can be referenced instead?

**Comment by maxfierke** [comment]
@SYU15 Sorry about the delay! Thanks for the heads up about the dead link. We'll go ahead and remove that link though, as it's likely not relevant for most folks these days, given the broad support in browsers for generator functions. I assume the content probably had to do with excluding the `regenerator-runtime` for generator function support in older browsers, to make the compiled source easier to view in a debugger.

For sufficiently modern Ember-CLI versions (from 2.13-ish or so and up), this can be done by tweaking the babel configuration via `ember-cli-build.js` (ember-cli-babel covers this in [more detail in their docs](https://github.com/babel/ember-cli-babel#usage))

**Comment by SYU15** [comment]
Yeah I wasn't sure if the article was even still helpful at this point given the topic/age of the post but dead links are a pet peeve of mine :) Thanks for looking into this @maxfierke!
