### ISSUE TITLE
ember-concurrency is not working in ember-utility

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [machty/ember-concurrency#347]
I am trying to use ember-concurrency tasks in my custom ember utility file. But it throws an error.

**Comment by maxfierke** [comment]
@vinodhrajamuralidharan Can you provide the error message and a stacktrace, and a snippet of the code for how you're using ember-concurrency within this utility file?

**Comment by vinodhrajamuralidharan** [comment]
If I write any task inside, I get build error.  Though I import at the top,  it does not understand the task keyword.

Is there anything I have to do differently?

**Comment by maxfierke** [comment]
@vinodhrajamuralidharan It would be hard for me to provide any guidance without some additional context (code, stacktrace, etc.)

**Comment by vinodhrajamuralidharan** [comment]
I understand. I get this error when I add a concurrency task in the utility file, 'error  Parsing error: Unexpected token :' and the code I added is, 

<img width="646" alt="Screenshot 2020-02-29 at 21 39 15" src="https://user-images.githubusercontent.com/8244992/75614756-47dc3280-5b3c-11ea-80cf-8bb8befb4328.png">
Correct me if I am doing anything wrong here in the utility file. I have used in other places and it works great. In the utility, I am trying the very first time.

**Comment by maxfierke** [comment]
@vinodhrajamuralidharan looks like `insights` is a function, not an ember object or class, so you cannot attach properties to it like that, (or ember-concurrency tasks)

You may be going for something like this?

```
export const insights = EmberObject.extend({
   store: service(),
   
   fetchItems: task(function*(params) {
     // ...
   })

   // ...
});
```

**Comment by vinodhrajamuralidharan** [comment]
I just tried in the plain util file. I understand now, ember-concurrency will only work on EmberObject and class. - Thanks
