### ISSUE TITLE
It should be possible to "background" a .perform

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#35]
From @sirzach in embercommunity:

> i’m hoping to be able to do something like make an ajax request and if it’s taking longer than `n` period of time, show something to user to let them know that work is still being done. anyone have any thoughts on how to get that going?

I don't think there's actually an idiomatic way to do this atm; the only thing I could think of was: 

```js
    import { task, race } from 'ember-concurrency';
​
    myTask: task(function * () {
      let displaySoon = this.get('displayMessageSoon', "Still working...");
      try {
        let val = yield $.ajax(...);
        return val;
      } finally {
        displaySoon.cancel();
      }
    }),
​
    displayMessageSoon: task(function * (delay, message) {
      yield timeout(delay);
      this.set('status', message);
    }),
```

But it's pretty gross to have to manually self-cancel... there should probably be something like `yield attach(this.get('displayMessageSoon',"still working"))`

**Comment by SirZach** [comment]
What I ended up implementing:
```javascript
submitTask: task(function * () {
    let promise = $.getJson(/* url */);
    let timer = this.get('timerTask').perform();
    yield promise;
    timer.cancel();
}),

timerTask: task(function * () {
    yield timeout(6000);
    this.set('takingTooLongStatusMessage', true);
}),
```

which seems effectively the same except without using the `try` `finally` block. Am I missing something by not using `try`?

**Comment by machty** [comment]
@SirZach The difference is if `myTask` gets canceled, you presumably want `displayMessageSoon` to cancel along with it, which will only happen if it's in the `finally` block (since ember-concurrency runs finally blocks upon cancelation).

**Comment by SirZach** [comment]
I see. So even though the child task isn't yielded it'll get canceled in the `finally`?

**Comment by machty** [comment]
The task will essentially `throw` a cancelation exception from wherever it happens to be yielded. In this case, it doesn't matter which promise is yielded, just that where it's paused when it's canceled, it'll run any `finally` blocks (and `catch` blocks too)
