### ISSUE TITLE
perform deprecation warning can be triggered outside a template

### ISSUE THREAD

**Issue by akatov** [machty/ember-concurrency#37]
e.g.
```js
myTask = task(function*(){...}),
_doSomething: Ember.on('didInsertElement', this.get('myTask').perform)
```
Not sure if there's another way to check whether one is in a template besides checking the context, though.
Also the above can be easily circumvented with a function definition or a bind..

Just thought I'd mention this..

**Comment by machty** [comment]
Can you come up with a real example? I don't think the one you supplied makes sense (you can't call `this.get()` as part of a class definition).

Either way, thanks for the heads up, though I'm not sure it's worth improving the message before I get rid of support entirely (though I'll still assert that `this` is the value expected and I'll fix the message when I remove support).

**Comment by akatov** [comment]
I guess a real example would be
```js
_doTaskLater: Ember.on('didInsertElement', function() {
  Ember.run.later(this.get('myTask'), perform, 2000);
})
```
even though this is still very artificial.
Something more real-world (what I'm actually using) would be if you were manually setting up listeners on an Ember.Evented object.

**Comment by machty** [comment]
That example should be just fine. I'm guessing when you saw that error, you tried something like:

    Ember.run.later(this.get('myTask.perform'), 2000);

which would cause the deprecation warning.

Also, for what it's worth, you probably want to do

    _doTaskLater: task(function * () {
      yield timeout(2000);
      this.get('myTask').perform();
    }).on('didInsertElement')

or perhaps just put the timeout at the beginning of myTask.

**Comment by nolaneo** [comment]
Hey @machty 👋  I'm still seeing this in our production app.

Here's a real world example. We have an auto save task which we debounce to every three seconds.

```javascript
let autoSaveTask = this.get('autoSave');
let autoSaveTimer = Em.run.debounce(this, autoSaveTask.perform, ENV.APP._3000MS);
this.set('autoSaveTimer', autoSaveTimer);
```

Passing a reference to `perform` as part of the debounce causes the template deprecation:

![image](https://cloud.githubusercontent.com/assets/2514088/21425032/731e1aba-c83e-11e6-930c-d391561d9083.png)

**Comment by machty** [comment]
@nolaneo I think the following change would fix:

```
Em.run.debounce(autoSaveTask, 'perform', ENV.APP._3000MS);
```
