### ISSUE TITLE
performing via onsubmit not working?

### ISSUE THREAD

**Issue by brandonweiss** [machty/ember-concurrency#38]
Is it just me or is performing a task via an `onsubmit` on a form not working? But an action that then calls perform works.

Does not work:

```handlebars
<form onsubmit={{perform createApp}}>
```

Works:

```javascript
actions: {

  createApp: function() {
    this.get('createApp').perform();
  }

}
```

```handlebars
<form {{action "createApp" on="submit"}}>
```

**Comment by brandonweiss** [comment]
To be clearer, it seems like what might be happening is the task fires but the form submission is not interrupted, so it submits the form to the current page and reloads.

**Comment by mmun** [comment]
Defining an `onsubmit` does not prevent the default behaviour from occurring. You'll need to call `event.preventDefault()` to get this behaviour.

Alternatively, just use `<form {{action (perform createApp) on='submit'}}>`.

**Comment by brandonweiss** [comment]
Ohhhh, right, that makes sense. The `onclick` isn't being interrupted either, it just doesn't have any side-effect so it doesn't matter. This example might be worth adding to the docs? I can imagine others might be confused as well.

**Comment by machty** [comment]
@brandonweiss you're not the first person to bring it up so it's probably worth a note in the docs. It's a bit unfortunate but this is actually in line with the behavior of normal Ember closure actions.

**Comment by brandonweiss** [comment]
Yeah, that totally makes sense—I just assumed something more magical was happening than it was.

**Comment by machty** [comment]
I'm not gonna clutter the docs with this particular case, so closing for now.

**Comment by theseyi** [comment]
Maybe add this to the FAQ? @machty Almost a year later and found this useful
