### ISSUE TITLE
Ember._setComputedDecorator is not a function

### ISSUE THREAD

**Issue by esbanarango** [machty/ember-concurrency#388]
```
"ember-cli": "3.22.0",
"ember-source": "3.23.1",
"ember-concurrency": "1.3.0",
```

https://github.com/emberjs/ember.js/pull/18826

<img width="900" alt="JSDoc__Source__index_js_and_package_json_—_workspace__Workspace_" src="https://user-images.githubusercontent.com/1156865/101069285-c81a4300-3567-11eb-9888-75f90f89676a.png">

**Comment by maxfierke** [comment]
Yep, in this case we use `_setClassicDecorator` instead, which should exist in versions where `_setComputedDecorator` does not. Does `_setClassicDecorator` not exist in 3.23?

**Comment by esbanarango** [comment]
![palm face](https://media.giphy.com/media/6yRVg0HWzgS88/giphy.gif) 

This error is actually coming from ember-animated.
