### ISSUE TITLE
Module '"ember-concurrency"' has no exported member 'lastValue'

### ISSUE THREAD

**Issue by oo6** [machty/ember-concurrency#404]
I'm using typescript in ember.
And when following the 2.0.0 upgrade guide, I replace ember-concurrency-decorators imports with ember-concurrency.
```diff
- import { lastValue } from 'ember-concurrency-decorators';
+ import { lastValue } from 'ember-concurrency';
```
I got:
```
error TS2305: Module '"ember-concurrency"' has no exported member 'lastValue'.
```

**Comment by maxfierke** [comment]
Hi @oo6 , thanks for the heads up! We definitely do export it (https://github.com/machty/ember-concurrency/blob/471864952ecba19c1199e8cfbbab4dce71d231b0/addon/index.js#L55) but it seems we're missing it from the TypeScript definitions. Will get those updated, thanks!
