### ISSUE TITLE
Error "@computed can only be used on accessors or fields..." using task decorator with modifiers

### ISSUE THREAD

**Issue by davideferre** [machty/ember-concurrency#416]
Writing code like explained in the tutorial ["Version 3: Preventing Concurrency (with Tasks)"](http://ember-concurrency.com/docs/tutorial/refactor) throws an exception:

> Error: Assertion Failed: @computed can only be used on accessors or fields, attempted to use it with seriesAddTask but that was a method. Try converting it to a getter (e.g. `get seriesAddTask() {}`)
![image](https://user-images.githubusercontent.com/10563913/111639467-93bb5180-87fb-11eb-891c-c49bab707388.png)

My code is:
```javascript
import { task } from 'ember-concurrency';
....
@task({ drop: true })
    *seriesAddTask() {
        ....
    }
```
I'm using ember-concurrency 2.0.3.

Writing it in this other way works fine:
```javascript
@(task(function* () {
    ....
}).drop()) seriesAddTask;
```

**Comment by maxfierke** [comment]
It sounds like you're maybe on an Ember version lower than 3.10? You may need to do this instead:

```javascript
@task({ drop: true })
seriesAddTask = function*() {
   // ...
}
```

**Comment by davideferre** [comment]
> It sounds like you're maybe on an Ember version lower than 3.10? You may need to do this instead:
> 
> ```js
> @task({ drop: true })
> seriesAddTask = function*() {
>    // ...
> }
> ```

No, I'm on ember 3.25...

**Comment by maxfierke** [comment]
> No, I'm on ember 3.25...

`@task` only uses `computed` for Ember versions below 3.10 or on ember-concurrency 1.x. My next guess is that something else in your app is probably loading an earlier version of ember-concurrency, and not ember-concurrency 2.x. `yarn why ember-concurrency` is a good way to find out what other versions of ember-concurrency might be present, if you're using Yarn.

**Comment by davideferre** [comment]
I'm using npm but you have found the problem!

> ├── ember-concurrency@2.0.3 
> └─┬ ember-google-maps@3.3.0
>  └── ember-concurrency@1.3.0
There's a way to solve the problem without uninstalling ember-google-maps?

**Comment by maxfierke** [comment]
With yarn, you can force it with `resolutions`. Not sure if there's an npm equivalent? Otherwise, you may need to contact the upstream author to relax the dependency range or have them push a new version with v2 support.

**Comment by davideferre** [comment]
> With yarn, you can force it with `resolutions`. Not sure if there's an npm equivalent? Otherwise, you may need to contact the upstream author to relax the dependency range or have them push a new version with v2 support.

Ok, thank you so much!
