### ISSUE TITLE
Overriding a parent/mixin object's task and then calling it with `this._super.perform()` doesn't work

### ISSUE THREAD

**Issue by mattmarcum** [machty/ember-concurrency#43]
I have a mixin with a task and I wanted to over-ride/extend it in a consuming service like this:
```
//some-mixin
Ember.mixin.create({
  sometask: task(function*(stuff){
    let thing = yield someAsyncFunc();
    return thing;
  })
})

//service
Ember.Service.extend(SomeMixin, {
  sometask: task(function * (stuff){
    let thing = yield this._super.perform(stuff);
    //do other async stuff here
  })
})
```
Wasn't sure if this would work and it doesn't - I get this error :
`<snip>Ember.Object.create no longer supports defining methods that call _super.</snip>`

So for right now I guess I'll have to re-implement the whole task in the service that is pulling in the mixin.  But I think this behavior would be nice-to-have...just not sure if its possible.

**Comment by machty** [comment]
I'm personally not a huge fan of using inheritance to wrap the behavior of overridden methods (and hence tasks), so I'm not sure how much I'd like to try and fix this, but what are you trying to use this for?

**Comment by machty** [comment]
Probably not gonna add support for this to e-c
