### ISSUE TITLE
`env.async` uses `run.once` but passes a new function

### ISSUE THREAD

**Issue by stefanpenner** [machty/ember-concurrency#437]
Both usages of `this.env.async` appear to rely on `run.once`, but pass dynamically created functions on each occurrence. Which means the de-duplication effort done by `run.once` is wasted:

file: `addon/-private/external/task-instance/executor.js` has:
103: this.env.async(() => this.proceedSync(yieldResumeType, value));
344: this.env.async(() => {

where `async` is implemented via `join(() => once(null, callback))` https://github.com/machty/ember-concurrency/blob/f53656876748973cf6638f14aab8a5c0776f5bba/addon/-private/ember-environment.js#L13

----

The most conservative change to correct ^ would like be: `join(() => schedule('actions', callback))`

**Comment by maxfierke** [comment]
oh snap, good find! We should fix that!

Out of curiosity, is there a measurable performance impact you're seeing from this?

**Comment by stefanpenner** [comment]
> Out of curiosity, is there a measurable performance impact you're seeing from this?

Nah, it's most likely a tiny paper-cut among many :P
