### ISSUE TITLE
Cannot reliably catch errors from a task?

### ISSUE THREAD

**Issue by mfenniak** [machty/ember-concurrency#44]
Hey.  First of all, gotta say, ember-concurrency is awesome.  Thanks to everyone involved for the work on this great library.  But I have a little issue that I'm not sure how I should handle.

I have a pretty simple task; keep reloading an Ember Data model until its 'state' property is 'complete'.

```js
reloadUntilComplete: task(function * (reportExecution) {
  while (reportExecution.get('state') !== 'complete') {
    yield reportExecution.reload();
    yield timeout(1000);
  }
}),
```

And I'm invoking the task as follows:

```js
const task = service.get('reloadUntilComplete').perform(someObject);
task.catch((err) => console.log('error occurred:', err));
```

But in the event that the first execution of 'reload' throws an error or returns a rejected promise, my 'catch' handler is never called, and instead I have an "Uncaught error" message logged.  The reason for this seems to be that the task is invoked immediately on the perform, has the error occur, and sends it to the promise's error handler... but the 'task.catch()' method has not yet been invoked.  Therefore it shows up as an uncaught error from RSVP's point-of-view.

I've worked around this issue by adding a ```yield timeout(0);``` to the beginning of my task; this delays the execution of actual logic until the next run-loop and allows my handler to attach.  But, this seems to be a fairly general issue that prevents a task's errors from being reliably handled.  Is there an approach that I'm missing on how to handle this?

**Comment by machty** [comment]
Can you try the latest release 0.6.2 and see if you're still running into this?

**Comment by mfenniak** [comment]
Upgrading to 0.6.2 seems to have resolved this completely.  I was able to remove the workaround ```yield timeout(0);``` from the top of my tasks, and all my unit tests that cover error-handling situations passed.

Thanks!
