### ISSUE TITLE
Getting `alias` error when upgrading to 4.2

### ISSUE THREAD

**Issue by npendery** [machty/ember-concurrency#460]
I get this error:

![Cursor_and_EmberQuickstart](https://user-images.githubusercontent.com/12616684/161323143-69dc781b-b0b8-4ae9-abec-dbe62ced3d4d.png)

**Comment by maxfierke** [comment]
@npendery This should not be a problem on e-c 2.x, as `@ember/computed` is not used internally anymore. However, from this, it looks like you're using ember-concurrency 1.x. There are no plans to update the 1.x branch further, but upgrading to 2.x should be relatively smooth for most folks.

(There's also an [upgrade guide](https://github.com/machty/ember-concurrency/blob/master/UPGRADING-2.x.md) for tips. In addition, it carries full support for the `@tracked` ecosystem, new features, and lots of bugfixes.)

**Comment by npendery** [comment]
Thanks for the response @maxfierke ! 

I am using the latest version so really confused how this gets into the `vendor.js` file....not sure if there was a common issue here but will keep digging

**Comment by maxfierke** [comment]
@npendery it's likely there's another add-on depending on an earlier version of `ember-concurrency`. If you use `yarn`, you can find out through the use of `yarn why ember-concurrency` or check out [ember-cli-dependency-lint](https://github.com/salsify/ember-cli-dependency-lint)

**Comment by npendery** [comment]
Oh jeez, youre totally right. Not sure how I missed that 🤦 

Thanks again!
