### ISSUE TITLE
`dropTask` not properly typed

### ISSUE THREAD

**Issue by mydea** [machty/ember-concurrency#485]
I am currently trying to migrate decorator-based tasks to the new (really cool!) async-based tasks.

However, in our TS app it seems that while this works and is nicely typed:

```js
myTask = task(async () => {});
```

This triggers type errors:

```js
myTask = dropTask(async () => {});
myTask = enqueueTask(async () => {});
```

Are these "shortcut" task definitions not supported anymore? Or is this a bug? :sweat_smile:

**Comment by machty** [comment]
Fixed in 2.3.3, thank you for the report!

**Comment by Techn1x** [comment]
I was very confused when the codemod refactored to dropTask etc. and I got errors, so I refactored them all to the general style with `task({ drop: true }, ...` :laughing: well there was a bunch of work I didn't need to do :)

**Comment by Techn1x** [comment]
(thanks for the fix, of course!)
