### ISSUE TITLE
3.0.0 doesn’t include #512?

### ISSUE THREAD

**Issue by backspace** [machty/ember-concurrency#528]
I’m seeing the same `Type 'ComputedProperty' is not generic` that I think #512 was meant to address but updating to 3.0.0 didn’t help. It looks like the 3.0.0 tag [doesn’t include](https://github.com/machty/ember-concurrency/commits/3.0.0) #512.

You can see the error is [here](https://github.com/cardstack/boxel/actions/runs/5006468037/jobs/8971788745#step:5:24) in CI and [is gone](https://github.com/cardstack/boxel/actions/runs/5007504400/jobs/8974200325?pr=337#step:5:12) after I switch to `master` for `ember-concurrency`.

Thanks for the work on this, it’s nice to move away from the `@types` packages!

**Comment by lozjackson** [comment]
we're also waiting for the changes in #512 to be released.  Will there be a new release soon that includes those changes?

**Comment by maxfierke** [comment]
Hey all, sorry about this! Should be included in 3.1.0: https://github.com/machty/ember-concurrency/releases/tag/3.1.0
