### ISSUE TITLE
Perfrom helper in Typescript

### ISSUE THREAD

**Issue by stevcooo** [machty/ember-concurrency#530]
Hello to you all,
I'm trying to migrate our project to Typescript in order to be able to enable `Glint`. In many of our `handlebars` components, we're using the `perform` helper. But now whenever I run the `glint` command I get a number of errors because `pefrom` is not recognized as a helper by `Glint`. 
Does somebody has stumbled on something similar? Is there any workaround or a PR that will migrate `perform` helper to TypeScript is the only solution?

**Comment by backspace** [comment]
I think the Typescript/Glint way is to `on 'whatever' this.taskName.perform` 🤔

**Comment by stevcooo** [comment]
I've resolved it by using `@gavant/glint-template-types` package.
```
import { PerformHelper } from '@gavant/glint-template-types/types/ember-concurrency/perform';
...
declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry {
  ....
  perform: typeof PerformHelper;
  ....
  }
}
```
