### ISSUE TITLE
Export types for helpers

### ISSUE THREAD

**Issue by Techn1x** [machty/ember-concurrency#532]
Follows on from this other issue, but it's closed since the author figured out a workaround - but I do think this addon should export types for helpers.
https://github.com/machty/ember-concurrency/issues/530

With Glint entering 1.0 and more applications adopting it, it's very useful to export these types as they end up being used in typed glint `.gts` files.

`perform` helper being the main example here. The other 2 helpers may not be much of a priority, not sure how widely used they are.

Looks like there's a type file declared here, if it helps!
https://github.com/Gavant/glint-template-types/blob/main/types/ember-concurrency/perform.d.ts

**Comment by bartocc** [comment]
I agree, it would be great to have `ember-concurrency` export the helper types instead of having to rely on `@gavant/glint-template-types`

**Comment by Techn1x** [comment]
Closing this - I think the types are exported in v4, but regardless the best way is to just use perform directly as a function
`{{on "click" this.myTask.perform}}`
or
`{{on "click" (fn this.myTask.perform "someArg")}}`
