### ISSUE TITLE
Babel issue with `ember-concurrency` 4.0.0

### ISSUE THREAD

**Issue by esbanarango** [machty/ember-concurrency#562]
"ember-concurrency": "4.0.0"
"ember-cli-babel": "^7.26.11"
"@babel/core": "7.23.9"

```
It appears you're attempting to use the new task(async () => { ... }) syntax, but the async arrow task function you've provided is not being properly compiled by Babel
```

**Comment by machty** [comment]
Hello, EC 4 requires you to register the async arrow Babel transform within your consuming apps/addons (this is because V2 Embroider addons can no longer automatically register things like Babel transforms). 

See the release notes: https://github.com/machty/ember-concurrency/releases/tag/4.0.0
