### ISSUE TITLE
Problem using it inside Ember Power Select

### ISSUE THREAD

**Issue by cibernox** [machty/ember-concurrency#57]
Hi, 

This is not really a problem but maybe I can get some guidance. I am refactoring Ember Power Select to use ember-concurrency internally and I've found a weird problem. Just installing `ember-concurrency` and restarting the server results in 

```
app.import is not a function
```

I'm sure there is a problem specific to EPS, since installing it in a fresh addon works ok. 
The only place in the addon where I'm using `app.import` is in the [index.js](https://github.com/cibernox/ember-power-select/blob/master/index.js), but I don't see any red light there.

Ideas?

**Comment by cibernox** [comment]
For the record, commenting [this line]() removes the error. The error is ultimately coming from babel.

**Comment by machty** [comment]
fixed in 0.7.3
