### ISSUE TITLE
Can't install ember-concurrency in a fresh project

### ISSUE THREAD

**Issue by flyrev** [machty/ember-concurrency#58]
In a fresh ember project:
$ ember install ember-concurrency
version: 2.4.0
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
Install failed. Could not find addon with name: ember-concurrency

**Comment by machty** [comment]
Did you by chance name the new project "ember-concurrency"?

**Comment by flyrev** [comment]
Yes, and I regret that now. Using a different name worked nicely. Today I learned! Thanks, and sorry.

**Comment by machty** [comment]
No worries!
