### ISSUE TITLE
Implement w async functions + cancellation

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#6]
Right now ember-concurrency tasks are driven by generator functions, but if/when async functions are supported, we should probably switch over to them.

Keeping an eye on [this](https://github.com/stefanpenner/random/tree/master/cancellation) for now.

**Comment by lolmaus** [comment]
I'm using async/await all over my Ember projects, especially in tests. What are you waiting for? ;)

**Comment by machty** [comment]
@lolmaus cancelation
