### ISSUE TITLE
Acceptance tests fail because of TaskCancelation

### ISSUE THREAD

**Issue by knownasilya** [machty/ember-concurrency#62]
```js
testem.js:775 TaskCancelation: TaskCancelation
    at Class.cancel (http://localhost:7357/assets/vendor.js:198319:19)
    at Class.spliceTaskInstances (http://localhost:7357/assets/vendor.js:197740:22)
    at Class.cancelAll (http://localhost:7357/assets/vendor.js:197732:12)
    at Class.cancelAll (http://localhost:7357/assets/vendor.js:199072:23)
    at Array.<anonymous> (http://localhost:7357/assets/vendor.js:199463:32)
    at Class.owner.willDestroy (http://localhost:7357/assets/vendor.js:199454:25)
    at invoke (http://localhost:7357/assets/vendor.js:14821:16)
    at Object.flush (http://localhost:7357/assets/vendor.js:14885:11)
    at Object.flush (http://localhost:7357/assets/vendor.js:14693:17)
    at Object.end (http://localhost:7357/assets/vendor.js:15048:25)
```

Not sure why it's happening..
I only have one task, inside of a service.

**Comment by machty** [comment]
Did this start happening after upgrading to a new ember-concurrency version, or is this a new test you're writing?

`TaskCancelation`s should only throw errors if you're using a task instance as a promise, i.e. if you did `someTask.perform().then(...)`; is it possible you're using `.then()` somewhere in your test case? Or perhaps you're returning `someTask.perform()` to ember qunit and _that's_ what's called `.then()` ?

**Comment by knownasilya** [comment]
So it erred with 0.7.1. I upgraded to 0.7.8 but no change. Checking for `then`s..

**Comment by knownasilya** [comment]
I am using a task as a promise. I added a `catch` and getting other errors.. `calling set on destroyed object`, so unrelated.

**Comment by knownasilya** [comment]
So i resolved the other issues, but still get the error, although it no longer fails my tests.

```js
testem.js:775 Basemap initialization failed: TaskCancelationconsole.(anonymous function) @ testem.js:775(anonymous function) @ theme-manager.js:61tryCatch @ vendor.js:68294invokeCallback @ vendor.js:68309publish @ vendor.js:68277publishRejection @ vendor.js:68212(anonymous function) @ vendor.js:46542invoke @ vendor.js:14821flush @ vendor.js:14885flush @ vendor.js:14693end @ vendor.js:15048run @ vendor.js:15170run @ vendor.js:35627willDestroy @ vendor.js:47890superWrapper @ vendor.js:37596willDestroy @ vendor.js:19806superWrapper @ vendor.js:37596invoke @ vendor.js:14821flush @ vendor.js:14885flush @ vendor.js:14693end @ vendor.js:15048run @ vendor.js:15170run @ vendor.js:35627destroyApp @ destroy-app.js:5afterEach @ module-for-acceptance.js:19callHook @ qunit.js:869runHook @ qunit.js:862process @ qunit.js:629begin @ qunit.js:611(anonymous function) @ qunit.js:671
```

**Comment by machty** [comment]
It sounds like there is some other place in your code where you call `.then()` on a task instance but don't `catch()` and it's getting canceled as part of the test teardown. My hunch is that ember-concurrency is doing the right thing here, but perhaps the error message could be better, and could give you a little more information about the name of the task that's failing.

**Comment by knownasilya** [comment]
> It sounds like there is some other place in your code where you call .then() on a task instance but don't catch() and it's getting canceled as part of the test teardown.

Will keep looking, thanks!

> perhaps the error message could be better, and could give you a little more information about the name of the task that's failing.

That would be nice!

**Comment by knownasilya** [comment]
So I only have one task, and only call `then` once, but my task doesn't actually return anything, maybe that's the issue? Basically I just do `resolve(task.perform())` in another part of the code.

**Comment by machty** [comment]
Yeah that'll do it; RSVP and the like will yell at you for any uncaught rejected promise, even if you don't "do" anything witwh it.

**Comment by machty** [comment]
Can I ask how/why you're using `resolve`? There might be a nicer way to structure the code that avoids the `resolve`/`.then()`

**Comment by knownasilya** [comment]
Basically I have a function `initializeBasemaps`, which listens for an event on the google map, and returns a promise. Inside this function I call the `setBaseTheme` task, so I resolve it since the `initializeBasemaps` function returns a promise.

**Comment by knownasilya** [comment]
I also see these:

```js
test-support.js:2490 Uncaught (in promise) Error: Called stop() outside of a test context
    at Object.stop (http://localhost:7357/assets/test-support.js:2490:10)
    at Class.asyncStart (http://localhost:7357/assets/vendor.js:54593:13)
    at asyncStart (http://localhost:7357/assets/vendor.js:46521:44)
    at Object.async (http://localhost:7357/assets/vendor.js:46535:7)
    at fulfill (http://localhost:7357/assets/vendor.js:68228:26)
    at handleMaybeThenable (http://localhost:7357/assets/vendor.js:68188:9)
    at resolve (http://localhost:7357/assets/vendor.js:68201:7)
    at sealed (http://localhost:7357/assets/vendor.js:68140:11)
```

Twice, where as I see the cancelation error 3 times. I added a `return RSVP.resolve()` to the task (I do `yield` within the task).

**Comment by knownasilya** [comment]
I have another error, so I'm going to investigate that and maybe it'll fix it..

**Comment by alvincrespo** [comment]
Yeah just had this issue, and dropping some notes in case anyone encounters this again:

**Problem**
```
  save: task(function*() {
    let tasks = [
      loadA.perform(),
      loadB.perform(),
    ];

    yield RSVP.all(tasks);
  }),

  actions: {
    onNext() {
      const save = get(this, 'save');
      
      // Handle the returned promise in the catch 
      save.perform()
        .then(() => {
          set(this, 'isConfirmed', true);
        })
        .catch(() => {});
    }
  }
```

In this example the catch doesn't do anything - which is not recommended. You should probably do something there 😄

**Comment by machty** [comment]
Can we close this issue?

**Comment by knownasilya** [comment]
Sure, if I have more issues I'll let you know.
