### ISSUE TITLE
RFC: Rename Task/TaskInstance

### ISSUE THREAD

**Issue by mmun** [machty/ember-concurrency#68]
In an effort to make things easier to talk about and teach I propose a couple renamings:

`TaskInstance` &rarr; `Task`
`Task` &rarr; `TaskManager`

The idea is that a "task" should be something with a definite ending, in that `task.isFinished` makes sense. `isFinished` wouldn't make sense on a task manager, because it will always be able to spawn more tasks in the future. That brings me to another point. It may be worth exploring `spawn` as an alternatives to `perform` to make it clearer that something is being created (a task). This could have an added benefit of giving encapsulated tasks more spotlight.

Conversationally, I think it will still be fine to continue referring to a task manager as a "task", especially in cases where there task manager only allows one concurrent task at a time.

**Comment by brandensilva** [comment]
👍  I'm all for improved naming conventions to simplify understanding.

Obviously this impacts old code so I imagine it wouldn't make its way into the project until a major point release; assuming others are on board.

**Comment by machty** [comment]
@brandensilva does it actually impact public APIs in any way?

**Comment by Turbo87** [comment]
FWIW I like the current naming, and I'm not convinced that the proposed names will be easier to understand 🤔
