### ISSUE TITLE
pausing tasks

### ISSUE THREAD

**Issue by lmcardle** [machty/ember-concurrency#71]
I have an array of objects, let's say 100 todos, which i want to delete. The API does not accept an array of objects to delete and so instead I have to issue the delete request one at a time. When the end user issues/starts the delete request, they may want to pause/resume at any point before all the tasks have completed.

Once an AJAX request has been made to the API server to delete an object, I am not able to cancel the request, as the request has been made and is out of the browsers hands. So when the user clicks "cancel", after starting a bulk delete request, what I want to do is 

1. pause only the "waiting" tasks....let the "running" tasks complete
2. give the user on option to resume/restart those tasks that are manually paused

Any thoughts on a way to achieve this?

**Comment by lmcardle** [comment]
Here is the implementation I used to get around e-c not supporting pause/resume. Right now this is tightly coupled to the delete action, but I've got the need to do this for many different kinds of bulk actions.

```
  _startBulkDelete(items) {
    let instance = this.get('_destroyManyItems').perform(items);
    this.set('_currentBulkDelete', instance);
  },

  _cancelBulkDelete() {
    this.get('_currentBulkDelete').cancel();
  },

  _pauseBulkDelete() {
      let currentTasks = this.get('_currentBulkDelete');
      currentTasks.cancel();

      let taskInstances = this.get('_taskInstances');
      let canceled = taskInstances.filterBy('state', 'canceled');

      let pausedItems = [];
      canceled.forEach((item) => {
        if (item.get('isDestroyed')) {
          // even though we canceled the task, the API continues with the delete
          // if the API deleted, add to succeeded tasks
          this.get('_successfulTasks').pushObject(item);
          this.get('_completedTasks').pushObject(item);
        } else {
          // if the API did not delete, add to paused so we can start again later
          pausedItems.pushObject(item.args[0]);
        }
      });

      let dropped = taskInstances.filterBy('state', 'dropped');
      dropped.forEach((item) => {
        pausedItems.pushObject(item.args[0]);
      });

      this.set('_pausedItems', pausedItems);
    },

    _resumeBulkDelete() {
      let pausedTasks = this.get('_pausedItems');
      this._startBulkDelete(pausedTasks);
    },

    _destroyManyItems: task(function *(items) {
      let taskInstances;

      taskInstances = items.map((item) => {
        return this.get('_destroyItem').perform(item);
      });

      this.set('_taskInstances', taskInstances);

      yield all(taskInstances);
      this.send('showFinishedModal');
    }),

    _destroyItem: task(function *(item) {
      yield item.destroyRecord().then(() => {
        this.get('_successfulTasks').pushObject(item);
        this.get('_completedTasks').pushObject(item);
      }, () => {
        this.get('_unsuccessfulTasks').pushObject(item);
        this.get('_completedTasks').pushObject(item);
      });
    }).maxConcurrency(1).enqueue()
  ```

**Comment by machty** [comment]
@lmcardle I'd have to think about this more but my gut instinct is that you might want to model each operation as a PendingOperation model that might internally use e-c tasks to implement the logic for hitting the server and performing any necessary async steps to accomplish that. And then you could have some service with a "runner" task that pops PendingOperations from a queue while some isPaused boolean flag is still flase and runs them one at a time and handles the custom logic for when things are allowed to cancel. I suppose something like this _could_ be added to e-c as a feature, but there's always going to be cases where it's best to model some custom async / state machine logic using plane ol objects and sprinkling in the e-c tasks where they help.

**Comment by machty** [comment]
@lmcardle is this still something you're interested in pursuing?

**Comment by lmcardle** [comment]
Yea I implemented the code I mentioned above. It'd be nice to have pause and resume as native but I understand your points. So for my use case I am good right now. Thanks.

**Comment by YoranBrondsema** [comment]
I'm having a similar case here. I am showing an animation that is implemented as an ember-concurrency task. Something like:

````
animationTask: task(function* () {
  // step 1
  yield someStep();
  // step 2
  yield theNextStep();
  // etc...
})
````

Now I want to pause it once it goes out of the user's viewport, and resume it once it's visible again. I solved it by wrapping each step into its own animation command object. Then the `animationTask` executes a sequence of such steps where after each step, we check whether the animation has been paused. So something like:

````
animationTask: task(function* () {
  for (let step of this.get('animationSteps')) {
    // each step is now wrapped into an object that has an 'execute' method
    yield step.execute.apply(this);

    if (this.get('isPaused')) {
      // this busy-waits until the 'isPaused' flag becomes false
      yield this.get('waitUntilResumedTask').perform();
    }
 }
}),
````

Now I can clearly see this being moved down to ember-concurrency. You would have the `pause` and `resume` methods on a `TaskInstance`. I think that after every async operation inside a task, you already check whether a task should be cancelled so at the same place it would be possible to put a check to see if the task is paused.

I can see some issues with this, namely the busy-waiting is far from ideal. For one, it's application-dependent: for instance in my case, I poll every 20ms as that is sufficient for this particular use case. However, I can imagine applications where you'd want an immediate resume.

Curious to hear your thoughts on this and if this is something you'd consider.
