### ISSUE TITLE
allSettled task aware yieldable

### ISSUE THREAD

**Issue by aaronbhansen** [machty/ember-concurrency#74]
Right now you have an "all" yieldable helper you're exporting that takes advantage of the taskAwareVariantOf method. Would it make sense to add a allSettled yieldable so we can handle the errors after all promises have completed? If so I could add a quick pull request to add it.

**Comment by machty** [comment]
Yeah, that sounds like a winner to me. Go for it :)

**Comment by machty** [comment]
Can you reproduce this travis failure locally?

<details>
  <summary>Failing travis errors</summary>
not ok 194 PhantomJS 2.1 - Unit: yieldables: allSettled does not cancel all other joined tasks if one of them fails
    ---
        actual: >
            Max depth.,Max depth.,Max depth.
        expected: >
            Max depth.,Max depth.,Max depth.
        stack: >
            callee$1$0$@http://localhost:7357/assets/tests.js:4211:31
            tryCatch@http://localhost:7357/assets/vendor.js:3823:44
            invoke@http://localhost:7357/assets/vendor.js:4090:30
            http://localhost:7357/assets/vendor.js:3856:28
            _takeSafeStep@http://localhost:7357/assets/vendor.js:103014:45
            _takeStep@http://localhost:7357/assets/vendor.js:103029:46
            invoke@http://localhost:7357/assets/vendor.js:14255:21
            flush@http://localhost:7357/assets/vendor.js:14321:17
            flush@http://localhost:7357/assets/vendor.js:14122:22
            end@http://localhost:7357/assets/vendor.js:14500:30
            run@http://localhost:7357/assets/vendor.js:14622:21
            run@http://localhost:7357/assets/vendor.js:34600:32
            http://localhost:7357/assets/tests.js:4259:26
            runTest@http://localhost:7357/assets/test-support.js:2688:32
            run@http://localhost:7357/assets/test-support.js:2673:11
            http://localhost:7357/assets/test-support.js:2815:14
            process@http://localhost:7357/assets/test-support.js:2474:24
            begin@http://localhost:7357/assets/test-support.js:2456:9
            http://localhost:7357/assets/test-support.js:2516:9
        Log: |
    ...
</details>

**Comment by aaronbhansen** [comment]
I tried in phantomjs and just got the error. I was running all the tests in chrome. I'll see if I can fix it in phantomjs.

**Comment by aaronbhansen** [comment]
Looks like phantom js adding extra into we aren't getting in chrome on the deep equals. I can add this hack and it fixes it. Deleting the specific object keys (line, stack, etc) should have worked, but wasn't so I had to reconstruct the object excluding known keys. 

If that is okay with you, i'll update it and tests should pass.

```
assert.equal(typeof allPromise.then, 'function');
let values = yield allPromise;
// Phantomjs adds extra meta data that needs to be removed for deepEqual
for (let i = 0; i < values.length; ++i) {
  let value = values[i];
  if (value.state === 'rejected') {
    let reason = value.reason;
    value.reason = { };
    let keys = Object.keys(reason);
    for (let j = 0; j < keys.length; ++j) {
      let key = keys[j];
      if (['line', 'sourceURL', 'stack'].indexOf(key) === -1) {
        value.reason[key] = reason[key];
      }
    }
  }
}
assert.deepEqual(values, [{ state: 'fulfilled', value: 'a' }, { state: 'rejected', reason: { wat: 'lol' } }, { state: 'fulfilled', value: 'c' }]);
```

**Comment by machty** [comment]
Sorry, meant to comment on the PR, not this issue, continuing discussion on the PR...
