### ISSUE TITLE
task().keepLatest() vs myTask.lastSuccessful.value

### ISSUE THREAD

**Issue by taras** [machty/ember-concurrency#76]
What's the difference between these to?

Can I omit `.keepLatest()` and still get the same results with `.lastSuccessful.value`?

**Comment by machty** [comment]
If I understand correctly, the difference is that `keepLatest`, like `drop`, will throttle the task from, say, hitting the server a bunch of times if the task is performed a bunch of times in a row. But unlike drop, if you try to perform while it's still processing a previous perform, it'll stash one perform to fire after that prior one completes (and if more performs happen, it'll "keep" the "latest" one). It's weird/hard to describe, but it fills a specific use case where you've got bursts of notifications that some data is stale and you want to drop all the "in-between" data fetches.

`.lastSuccessful.value` might work in a lot of similar cases for displaying the result but it wouldn't prevent a burst from requests from being sent to the server.

**Comment by taras** [comment]
@machty sorry I couldn't respond when you messaged and then forgot. Thank you for the response. It's exactly what I was looking for.
