### ISSUE TITLE
`.maxConcurrency()` on its own should throw an error

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#77]
If you just do `task(...).maxConcurrency(n)` without applying any other modifier, we should probably raise an error and tell you to use one of the other task modifiers for clarity. This would be a "breaking" change but it would nudge you to clarify intent, whereas by default today `.maxConcurrency()` on its own behaves the same as `.enqueue().maxConcurrency(n)`, which has caused some confusion because some people think it implies `.drop()`, others `.restartable()`, etc.

**Comment by ddoria921** [comment]
Gonna take a shot at this
