### ISSUE TITLE
bug: task seems to continue running in some cases of `restartable()`

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#78]
reported by @shoxter

If you type a bunch of characters on http://ember-concurrency.com/#/docs/examples/autocomplete, wait for search results, and then delete all the characters, it shouldn't fire a query to the server, but it does, with a single character. Need to look into it more but seems like possible a bug with restartable where if the new task completed synchronously, a prior task might not be cancelled. Seeeeeems bad.

**Comment by sukima** [comment]
Also holding down the <kbd>Backspace</kbd> seems to fire on every character removal. Not sure if that is related.

**Comment by machty** [comment]
Nevermind, this is actually due to ember-power-select not firing its `search` action when the string is empty: https://github.com/cibernox/ember-power-select/issues/354
