### ISSUE TITLE
willDestroy override prevents unit testing component functionality with mixins

### ISSUE THREAD

**Issue by blimmer** [machty/ember-concurrency#87]
[example of issue](https://github.com/blimmer/ember-cli-example-app-for-github/pull/1/files)
[failing tests](https://travis-ci.org/blimmer/ember-cli-example-app-for-github/builds/168989654)

I added ember concurrency to a component I have that includes [ember-keyboard](https://github.com/null-null-null/ember-keyboard) to allow users to use hotkeys for speed.

There are a few methods in this class that I need to unit test. Most all of my tests for this component are integration tests, but there is some logic dealing with scrolling that is not suitable for integration tests, and I need to use a unit test to mock and test this behavior.

By adding any task, I start to get this error when the unit test is tearing down the container:

```
Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.
```

I tracked it down to the `_cleanupOnDestroy` method in ember concurrency. https://github.com/machty/ember-concurrency/blob/cd462243bd949b0570f632a2b34cff63234a7d79/addon/utils.js#L88

It seems that the way it's applying the super `willDestroy`s causes this error, as the ember-keyboard mixin [implements a willDestroy](https://github.com/null-null-null/ember-keyboard/blob/1def7ee62d369f6533daf89f5d27bc4c8dc00578/addon/mixins/ember-keyboard.js#L28) and it's called during teardown of the test.

Aside from not using unit tests at all for components (I think there's an argument for some limited cases where their use is necessary), is there any kind of workaround to make this work?

**Comment by blimmer** [comment]
I found https://github.com/emberjs/ember.js/issues/11135 which somewhat describes the issue I'm seeing here. If I change my sample test from:

```javascript
    it('can just create the subject', function() {
      let component = this.subject();
      // ...
    });
```

to

```javascript
    it('can just create the subject', function() {
      let component = this.container.lookup('component:foo-bar');
      // ...
    });
```

it seems to work. 

That said, it's still weird that commenting out the task entirely allows the test to pass. It still feels like ember-concurrency is mucking with something that is supposed to "just work" in unit tests.

**Comment by machty** [comment]
Can you confirm that this is still broken on version 0.7.15?

**Comment by blimmer** [comment]
This patch fixed the problem for me. Thank you!
