### ISSUE TITLE
Adding a task to an object breaks willDestroy

### ISSUE THREAD

**Issue by cibernox** [machty/ember-concurrency#88]
Repo with a reproducible error: https://github.com/cibernox/bug-in-ember-concurrency

#### Steps:
1. Run the app
2. Visit `http://localhost:4200/tests?filter=Acceptance%20|%20Main`
3. Open the console to see the logs

#### What is wrong
The `willDestroy` method seems to be called not with the component, but with some subclass of it, that has a different `guid` and is, in summary, an entirely different object.

If you comment the task in [app/components/test-component.js](https://github.com/cibernox/bug-in-ember-concurrency/blob/master/app/components/test-component.js#L6) the componen behaves as expected.

#### Any bisect?

Yes, this works fine in `0.7.10` and wrong in `0.7.11`

**Comment by machty** [comment]
Fixed in 0.7.15

**Comment by cibernox** [comment]
![fast](http://i.giphy.com/SW3PNayoSGXao.gif)
