### ISSUE TITLE
Use perform helper in a subexpression

### ISSUE THREAD

**Issue by alidcastano** [machty/ember-concurrency#92]
As far as I know, you can only use the `perform` helper in a regular expression. 

`<button onclick={{perform }}>{{duration}}</button>`

But if I want to pass a task to a component, I currently find myself sending an action that then calls the perform function, which feels redundant.

It'd be nicer to just do this: 

`{{component on-change=(perform 'save')}}`

Would it be possible to make the perform helper work with subexpressions?

**Comment by machty** [comment]
I believe this already works?

https://ember-twiddle.com/1fc2fbe532d7bcf4a61202eb252200f7?numColumns=2&openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by alidcastano** [comment]
Oh, I couldn't find an example in the documentation, so didn't try playing with it. But 
it indeed does work once I set the `perform` task as a variable, not a string. Thanks.

**Comment by machty** [comment]
Cool, yeah, I don't think we'd want to implement the string approach even if the ember internals let us. Can we close this issue then?

**Comment by alidcastano** [comment]
Yeah thanks
