### ISSUE TITLE
Browser debugger source looks nothing like actual source

### ISSUE THREAD

**Issue by bgentry** [machty/ember-concurrency#95]
This is maybe related to #25 but thought I'd open a separate issue in case I'm wrong and you just want to close this :)

One thing I've run into with the debugging experience is that the source code I see when I'm debugging in my browser looks nothing like the code in my editor. Compare the original version:

```js
  loadData: task(function* (sensorId) {
    debugger;
  }).restartable(),
```

to the browser debugger version:

```js
    loadData: (0, _emberConcurrency.task)(regeneratorRuntime.mark(function callee$0$0(sensorId) {
      return regeneratorRuntime.wrap(function callee$0$0$(context$1$0) {
        while (1) switch (context$1$0.prev = context$1$0.next) {
          case 0:
            debugger;

          case 1:
          case 'end':
            return context$1$0.stop();
        }
      }, callee$0$0, this);
    })).restartable(),
```

Is this something inherent in the generators feature that makes this addon work, or is there some kind of path forward to making the source I see in my debugger actually look like the original source?

**Comment by Cryrivers** [comment]
Babel transpiles generation functions to definite state machines, which needs a runtime (i.e. regenerator). If you want to debug it in latest browsers which supports generator functions. You can simply put
```js
 babel: {
    blacklist: ['regenerator']
 }
```
in your `ember-cli-build.js`, so Babel will leave generator functions as-is.
